// The rows supabase/seed/portal_test_rpr.sql leaves on RPR, exported from the
// live project on Sep 25 2026. Tokens stand in for the test users' JWTs.
const CO = '4cfa6db6-5cee-4dbc-8d84-a95dd5eba6ae';
const OWNER = '89ccf1f9-7044-48b2-8304-0a5738c1ee3f', SAM = '1bb928fa-8ec4-4fe2-a033-8fb266233aa1';
export const USERS = {
  'tok-owner': { id: '0b7e5a52-2f1c-4c8e-9a61-7f0a1c2b3d01', email: 'vedikabhasin+rpr-owner@gmail.com' },
  'tok-sam':   { id: '0b7e5a52-2f1c-4c8e-9a61-7f0a1c2b3d02', email: 'vedikabhasin+rpr-sam@gmail.com' },
  'tok-stranger': { id: '99999999-0000-0000-0000-000000000009', email: 'stranger@example.com' },
};
const C = (key) => CARDS.find((c) => c.card_key === key).id;
export const CARDS = [
 ['f3ad8c30-026b-4a97-91cf-23bc7b7eb58e','rpr-01','pillar',"WebAR After 8th Wall: Buyer's Guide","8th Wall's hosted platform ended February 28, 2026. Every guide to what comes next is written by a platform selling itself. RPR can write the neutral one.","Search '8th Wall alternatives' and every result is a vendor: Zapworks, Kivicube, Blippar, Arloopa. The engine is now MIT open source without SLAM, VPS, Maps, or hand tracking. Your 'Is WebAR Better than AR Apps?' page predates all of it and folds into this pillar.",['webar','platforms','timely'],[['8th Wall open source announcement','8th Wall','https://8thwall.org/blog/8th-wall-open-source'],['8th Wall shutdown: 2026 WebAR guide','Kivicube','https://www.kivicube.com/post/augmented-reality-after-8th-wall-shutdown-your-2026-guide-to-the-right-webar-platform/'],['Mattercraft for 8th Wall developers','Zapworks','https://zap.works/mattercraft-for-8th-wall-studio-developers/'],['Blippar vs 8th Wall in 2026','Blippar','https://www.blippar.com/blippar-vs-8th-wall-which-webar-platform-should-you-choose-in-2026/'],['WebAR Insights','Rock Paper Reality','https://rockpaperreality.com/insights/web-ar/']],'2026-09-14',0],
 ['555a6ac1-4ae5-4e64-891b-bac19c77021b','rpr-02','pillar','Google Maps AR for Brands','Location-based AR inside Google Maps needs no app and no QR code. RPR shipped the first-of-its-kind launch and has the award to prove it.','Your Paris landmarks launch with Google Arts and Culture was covered by Forbes, and won the 2025 Auggie Award for AR in Google Maps. No page on your site explains how a brand buys it.',['location-ar','owned-proof'],[['Google Maps introduces AR for Paris landmarks with Rock Paper Reality','Forbes','https://www.forbes.com/sites/charliefink/2024/11/11/google-maps-introduces-ar-for-paris-landmarks-by-rock-paper-reality/'],['First-of-its-kind AR content launch in Google Maps','Rock Paper Reality','https://rockpaperreality.com/our-work/first-of-its-kind-ar-content-launch-in-google-maps-in-collaboration-with-google-arts-and-culture/'],['Insights (Auggie Award 2025)','Rock Paper Reality','https://rockpaperreality.com/insights/']],'2026-09-14',1],
 ['fcd4493e-a61a-4f5f-8214-411f4b3d1209','rpr-03','pillar','AR Glasses for Brands: What to Build',"The first glasses wave is audio, not holograms. Android XR launches audio glasses this fall and display glasses have no date. Brands should build for voice and navigation now, and for visual AR on Snap's Specs.","Google confirms Android XR audio glasses with Gentle Monster and Warby Parker this fall. Display glasses are listed as 'stay tuned'. Snap's display Specs are reportedly priced at $2,500. Navigation is a launch feature, which is where your Google Maps work lands. Your Vision Pro piece is written for a headset moment that has passed.",['glasses','timely','location-ar'],[['Android XR at I/O 2026','Google','https://blog.google/products-and-platforms/platforms/android/android-xr-io-2026/'],['Android XR devices','Android','https://www.android.com/xr/'],["Snap's AR glasses with display reportedly beat Android XR to launch",'9to5Google','https://9to5google.com/2026/05/22/snap-ar-glasses-spectacles-price-release-date-report/']],'2026-09-14',2],
 ['263f1ea9-6a1e-47b5-9f9b-44f9800fcb03','rpr-04','insight','AR for Events: Win the AI Overview',"RPR is the #1 result for 'augmented reality in events', yet Google's AI Overview above it quotes Onirix. Restructure the page so the answer engine quotes RPR.",'Google search, September 24, 2026: your page is the first organic result, directly beneath an AI Overview citing Onirix and a LinkedIn post.',['refresh','events','ai-search'],[['Google search: augmented reality in events (Sep 24, 2026)','Google','https://www.google.com/search?q=augmented+reality+in+events'],['Augmented Reality for Events','Rock Paper Reality','https://rockpaperreality.com/insights/ar-use-cases/augmented-reality-for-events/']],'2026-09-14',3],
 ['fdf2ba24-f53a-4817-a2c5-389eb27e9878','rpr-05','insight','VR in Museums: Cost and Timeline','You rank top 3 for what VR does in museums. The next thing a museum director searches is what it costs, and nobody answers it.',"Google search, September 24, 2026: 'How Virtual Reality is Transforming Museums' ranks top 3. Cost searches return museums' own ticketed VR attractions, not a buyer's guide.",['museums','buyer-intent'],[['Google search: virtual reality in museums (Sep 24, 2026)','Google','https://www.google.com/search?q=virtual+reality+in+museums'],['Insights','Rock Paper Reality','https://rockpaperreality.com/insights/']],'2026-09-14',4],
 ['50023ddd-baf5-4df2-8c00-8a08680eb33c','rpr-06','insight','Replacing 8th Wall VPS With Google Geospatial',"8th Wall's VPS is gone. For location-anchored campaigns, Google's Geospatial stack is the replacement, and RPR has already shipped on it.",'Links your two pillars: the 8th Wall buyer\'s guide and Google Maps AR for Brands. Built on your Google Maps launch.',['location-ar','webar'],[['8th Wall open source announcement','8th Wall','https://8thwall.org/blog/8th-wall-open-source'],['Geospatial Creator: world-scale AR in minutes','Google Developers','https://developers.googleblog.com/en/create-world-scale-augmented-reality-experiences-in-minutes-with-googles-geospatial-creator/'],['First-of-its-kind AR content launch in Google Maps','Rock Paper Reality','https://rockpaperreality.com/our-work/first-of-its-kind-ar-content-launch-in-google-maps-in-collaboration-with-google-arts-and-culture/']],'2026-09-21',5],
 ['ddb56fd1-080f-4f20-bd22-da0165c358e4','rpr-07','insight','AI in XR Production: Where Budget Moved',"Generative AI didn't make immersive cheaper. It moved budget from building assets to designing the experience.","Builds on Preston Platt's AWE USA 2025 session, which lives on your Insights page only as an event recap.",['ai','production'],[['Insights (AWE USA 2025: How AI Supercharged XR)','Rock Paper Reality','https://rockpaperreality.com/insights/']],'2026-09-21',6],
 ['966caff1-77f1-4684-b4f5-c2930b536841','rpr-08','insight','Experiential AR ROI: What to Measure',"Events buyers ask what an activation returned. Give them the four numbers that answer it, and the one that doesn't.","The follow-up to your #1 events page. Extends Omead Sinai's AWE USA 2025 talk on why events matter more than ever.",['events','buyer-intent'],[['Augmented Reality for Events','Rock Paper Reality','https://rockpaperreality.com/insights/ar-use-cases/augmented-reality-for-events/'],['Insights (AWE USA 2025: Why Events Matter More Than Ever)','Rock Paper Reality','https://rockpaperreality.com/insights/']],'2026-09-21',7],
 ['720838d9-929b-4ce1-a4af-0d724eab1533','rpr-09','insight','Gaussian Splatting for Museum Tours','Splats capture a gallery in an afternoon at photographic realism. For museums and attractions, that changes what a virtual tour costs.','Pairs your existing Gaussian Splatting article with the museum buyers you already rank for. Leaves the original article untouched.',['3d','museums'],[['Gaussian Splatting: When Does it Make Sense to Use and Why?','Rock Paper Reality','https://rockpaperreality.com/insights/3d-vfx/gaussian-splatting-when-does-it-make-sense-to-use-and-why/']],'2026-09-21',8],
 ['852dacf3-b163-4670-a86c-269128316e98','rpr-10','insight','Location-Based AR for Tourism Boards','Tourism boards want visitors to stay longer at a site. Location AR in Maps puts the story on the landmark itself, with no app to download.','Connects your tourism use-case page to the Google Maps pillar and the Paris landmarks launch.',['location-ar','tourism'],[['AR in Tourism and Travel','Rock Paper Reality','https://rockpaperreality.com/insights/ar-use-cases/augmented-reality-in-tourism-and-travel/'],['First-of-its-kind AR content launch in Google Maps','Rock Paper Reality','https://rockpaperreality.com/our-work/first-of-its-kind-ar-content-launch-in-google-maps-in-collaboration-with-google-arts-and-culture/']],'2026-09-21',9],
].map(([id, card_key, format, title, angle, evidence, tags, src, drop_date, sort_order]) => ({ id, company_id: CO, card_key, format, title, angle, evidence, tags,
  sources: src.map(([title, publisher, url]) => ({ title, publisher, url })), drop_date, sort_order }));
export function freshDb(overrides = {}) {
  return {
    companies: [{ id: CO, slug: 'rpr-k7m2qx', name: 'Rock Paper Reality', contact_first_name: 'Patrick', hub_unlocked: false,
      subscription_status: 'canceled', subscription_ends_at: '2026-10-25T20:38:34+00:00', ...(overrides.company || {}) }],
    members: [
      { id: OWNER, company_id: CO, user_id: USERS['tok-owner'].id, role: 'owner', display_name: null, avatar_shape: 'ghost', onboarding: {}, created_at: '2026-09-25T20:45:28.313927+00:00' },
      { id: SAM, company_id: CO, user_id: USERS['tok-sam'].id, role: 'member', display_name: 'Sam', avatar_shape: 'blob', onboarding: {}, created_at: '2026-09-25T20:45:28.313928+00:00' },
    ],
    cards: structuredClone(CARDS),
    decisions: [
      ['rpr-01', null, 'like'], ['rpr-02', null, 'fasttrack'], ['rpr-04', null, 'like'], ['rpr-06', null, 'like'], ['rpr-07', null, 'pass'],
      ['rpr-02', SAM, 'pass'], ['rpr-04', SAM, 'save'], ['rpr-06', SAM, 'like'],
    ].map(([k, m, a], i) => ({ id: 'd' + i, company_id: CO, card_id: C(k), member_id: m, action: a, updated_at: '2026-09-25T20:45:28Z' })),
    swipe_events: [
      [4, 'rpr-01', null, 'like', 'sales', '2026-09-15T16:11:00+00:00'], [5, 'rpr-02', null, 'fasttrack', 'sales', '2026-09-15T16:12:00+00:00'],
      [6, 'rpr-04', null, 'like', 'sales', '2026-09-15T16:13:00+00:00'], [7, 'rpr-06', null, 'like', 'sales', '2026-09-15T16:14:00+00:00'],
      [8, 'rpr-07', null, 'pass', 'sales', '2026-09-15T16:15:00+00:00'], [11, 'rpr-06', SAM, 'like', 'portal', '2026-09-22T09:31:00+00:00'],
      [9, 'rpr-02', SAM, 'pass', 'portal', '2026-09-22T09:32:00+00:00'], [10, 'rpr-04', SAM, 'save', 'portal', '2026-09-22T09:33:00+00:00'],
    ].map(([id, k, m, a, s, t]) => ({ id, company_id: CO, card_id: C(k), member_id: m, action: a, source: s, created_at: t })),
    signals: [{ id: 's1', company_id: CO, text: "RPR ranks #1 for 'augmented reality in events', but Google's AI Overview above it cites Onirix.", source: 'Google search', signal_date: '2026-09-24', created_at: '2026-09-25T18:56:44Z' }],
    articles: [
      { id: '1bbb84f3-6ff2-4c6e-aeb2-4e39636036d7', company_id: CO, card_id: C('rpr-01'), format: 'pillar', title: "WebAR After 8th Wall: Buyer's Guide", status: 'delivered',
        body_html: "<h2 class=\"gd-h\">8th Wall is open source. Now what?</h2><p style=\"margin:0\">On February 28, 2026, 8th Wall's hosted platform shut down. The engine is now MIT-licensed, but SLAM, VPS, Maps and hand tracking did not come with it. <strong>Every guide to what comes next is written by a vendor.</strong></p><h2>What you actually lost</h2><ul><li>World tracking (SLAM)</li><li>Visual positioning (VPS)</li><li>Hand tracking</li></ul><h3>The shortlist</h3><p>Zapworks, Kivicube, Blippar and Arloopa each cover part of it. <a href=\"https://8thwall.org/blog/8th-wall-open-source\">Read the announcement</a>.</p>",
        google_doc_url: 'https://docs.google.com/document/d/portal-test-rpr-01/edit', delivered_at: '2026-09-22T14:00:00+00:00', live_at: null, created_at: '2026-09-25T20:45:28Z' },
      { id: '3e4c4873-4b2b-4bac-846e-00cfbf2d450b', company_id: CO, card_id: C('rpr-04'), format: 'insight', title: 'AR for Events: Win the AI Overview', status: 'approved_unwritten', body_html: null, google_doc_url: null, delivered_at: null, live_at: null, created_at: '2026-09-25T20:45:28Z' },
      { id: 'a25ceeb1-3df8-47ed-8938-4bc2fe7b7e0e', company_id: CO, card_id: C('rpr-05'), format: 'insight', title: 'VR in Museums: Cost and Timeline', status: 'approved_unwritten', body_html: null, google_doc_url: null, delivered_at: null, live_at: null, created_at: '2026-09-25T20:45:28Z' },
    ],
    notes: [],
  };
}
