-- Import for Another Reality Studio (anotherreality-5nu2ok). Generated from clients/anotherreality-5nu2ok.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('anotherreality-5nu2ok', 'Another Reality Studio', null, null, 'your Celestial Park twin and AR work, and the questions venue teams ask before they fund a twin', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'ars-01', 'long_form', 'Venue Digital Twins: Validate Before Opening', 'Large enterprises hold 66.41% of the 2026 digital twin market, per Fortune Business Insights. A twin earns its cost when teams can test lighting, safety and show programming before construction ends.', 'Your Celestial Park twin for Universal Epic Universe ran in Unreal Engine 5, with DMX control through Art-Net and sACN, so lighting could be pre-programmed on grandMA3 consoles. It measured candela, lumen and lux before the 2025 opening. Your "up to 60% faster" claim is self-reported, so confirm the basis.', '{digital-twins,long-form,venue-design}'::text[], '[{"title": "Celestial Park", "publisher": "Another Reality Studio", "url": "https://anotherreality.studio/universal-celestial-park/"}, {"title": "digital twin market", "publisher": "Fortune Business Insights", "url": "https://www.fortunebusinessinsights.com/digital-twin-market-106246"}]'::jsonb, 0 from companies where slug = 'anotherreality-5nu2ok'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'ars-02', 'short_insight', 'Synthetic Training Data From a Digital Twin', 'A Sept 2026 market note says twins are shifting from visualization tools to an operational backbone. Generating synthetic images for computer vision is one concrete operational use.', 'Your Celestial Park page lists synthetic datasets for object detection, segmentation, defect detection and autonomous navigation. It frames these as covering edge cases, such as rare weather or lighting, that are impractical to capture physically.', '{synthetic-data,short-insight,digital-twins}'::text[], '[{"title": "Celestial Park", "publisher": "Another Reality Studio", "url": "https://anotherreality.studio/universal-celestial-park/"}, {"title": "digital twin market", "publisher": "GlobeNewswire", "url": "https://www.globenewswire.com/news-release/2026/09/08/3357954/0/en/digital-twin-market-demand-innovation-market-size.html"}]'::jsonb, 1 from companies where slug = 'anotherreality-5nu2ok'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'ars-03', 'short_insight', 'WebAR After 8th Wall: Plan the Migration', '8th Wall access ended Feb 28, 2026, and hosted content goes dark Feb 28, 2027. Teams running WebAR campaigns need a migration plan, and platform risk now belongs in the scoping conversation.', 'Your AR Everywhere case study covers geolocated, cross-platform AR with guided narratives and branded activations. Your blog already has a WebAR versus app article, so this is a platform-risk update. Confirm what AR Everywhere runs on before claiming independence.', '{webar,short-insight,geolocated-ar}'::text[], '[{"title": "case studies", "publisher": "Another Reality Studio", "url": "https://anotherreality.studio/case-studies/"}, {"title": "WebAR vs app AR", "publisher": "Another Reality Studio", "url": "https://anotherreality.studio/webar-appar/"}, {"title": "WebAR landscape 2026", "publisher": "Blippar", "url": "https://www.blippar.com/best-webar-platforms-for-agencies-2026/"}]'::jsonb, 2 from companies where slug = 'anotherreality-5nu2ok'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
