-- Import for Canopy (canopy-72uicf). Generated from clients/canopy-72uicf.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('canopy-72uicf', 'Canopy', 'Ori', 'Ori', 'your content filter and chatbot work, and the questions parents ask before they trust a safeguard', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r3-49', 'short_insight', 'Chatbot Filtering Without the Provider''s Help', 'California SB 243 (effective January 1 2026) puts duties on companion-chatbot operators, with a private remedy for people who suffer injury. The law binds some operators; the protection gap is every chatbot and account a child can reach that it does not cover.', 'Your March 2026 filter works at the browser and device level across ChatGPT, Gemini, Grok, Perplexity and Claude, routes native apps to filtered browser versions, and holds even when a family switches accounts. You explained the feature already; the deeper follow-up is the protection boundary, what happens in native apps, and how the filter keeps pace with changing outputs.', '{ai-safety-for-minors,short-insight,regulation}'::text[], '[{"title": "Canopy''s Chatbot Content Filter", "publisher": "Canopy", "url": "https://canopy.us/blog/chatbot-content-filter/"}, {"title": "California SB 243 compliance requirements for AI companion chatbots", "publisher": "Gunderson Dettmer", "url": "https://www.gunder.com/en/news-insights/insights/client-insight-california-sb-243-new-compliance-requirements-for-operators-of-ai-companion-chatbots"}, {"title": "Our Technology", "publisher": "Canopy", "url": "https://canopy.us/our-technology/"}]'::jsonb, 0 from companies where slug = 'canopy-72uicf'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r3-50', 'long_form', 'Age Verification Laws Do Not Filter Content', 'Texas''s App Store Accountability Act took effect May 28 2026 after a Fifth Circuit stay, with further state laws on their own timelines. These laws move age categories and consent signals between stores and developers; they do not inspect what a child sees inside an app.', 'Your position is that screen-time limits and content filtering are different jobs, and your product replaces explicit images inside otherwise allowed pages in milliseconds. A piece that tells parents which job each safeguard actually does is a traffic piece with a multi-year shelf life.', '{age-verification,long-form,product-positioning}'::text[], '[{"title": "Key Developments With State App Store Accountability Acts", "publisher": "Wiley", "url": "https://www.wiley.law/alert-Key-Developments-With-State-App-Store-Accountability-Acts-as-Texas-Act-Takes-Effect"}, {"title": "Screen Time Limits vs Content Filtering", "publisher": "Canopy", "url": "https://canopy.us/blog/screen-time-limits-vs-content-filtering/"}, {"title": "homepage", "publisher": "Canopy", "url": "https://canopy.us/"}]'::jsonb, 1 from companies where slug = 'canopy-72uicf'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r3-51', 'short_insight', 'Replacing Pixels Beats Blocking Pages', 'Blocking a whole website is blunt when the unwanted material is one image on an otherwise useful page. Selective replacement needs a classifier fast enough that the page still loads normally, and honest numbers on what it gets wrong.', 'Your patented SafeSmart filter replaces explicit images with white rectangles in browsers and some apps, decides in milliseconds, and serves 200,000-plus families by your own count. You publish no latency distribution, false-positive rate or statement of where the model runs; the article that does would separate you from every blocklist competitor.', '{real-time-image-classification,short-insight,patent-proof}'::text[], '[{"title": "Our Technology", "publisher": "Canopy", "url": "https://canopy.us/our-technology/"}, {"title": "Chatbot Content Filter", "publisher": "Canopy", "url": "https://canopy.us/blog/chatbot-content-filter/"}, {"title": "Key Developments With State App Store Accountability Acts", "publisher": "Wiley", "url": "https://www.wiley.law/alert-Key-Developments-With-State-App-Store-Accountability-Acts-as-Texas-Act-Takes-Effect"}]'::jsonb, 2 from companies where slug = 'canopy-72uicf'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
