-- Import for Capital XR (capitalxr-3tbkt1). Generated from clients/capitalxr-3tbkt1.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('capitalxr-3tbkt1', 'Capital XR', null, null, 'your PlaneVR and ImmersiveXR work, and the questions training leads ask before they buy VR', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'cxr-01', 'long_form', 'Flight School VR: Measure Time to Solo', 'Boeing''s 2026 outlook calls for 674,000 new pilots worldwide by 2045, and two-thirds of that demand replaces retirees. VR procedural training only pays off if it frees aircraft and instructor time, so judge it on hours to solo, not novelty.', 'Your Learn2Fly testimonial reports a student who went solo in 10.7 hours against a usual 13.0. Your PlaneVR page claims a 15% bottom-line gain. Both rest on one school''s account and your own estimate, so show the method before the number.', '{flight-training,long-form,pilot-pipeline}'::text[], '[{"title": "Pilot and Technician Outlook", "publisher": "Boeing", "url": "https://www.boeing.com/commercial/market/pilot-technician-outlook"}, {"title": "Boeing retirement wave", "publisher": "Aviation Week", "url": "https://aviationweek.com/mro/workforce-training/boeing-retirement-wave-underscores-need-training-overhaul"}, {"title": "PlaneVR for flight schools", "publisher": "Capital XR", "url": "https://capitalxr.com.au/planevr-for-flight-schools"}]'::jsonb, 0 from companies where slug = 'capitalxr-3tbkt1'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'cxr-02', 'short_insight', 'OEM Training in VR: Induct Without Shutdowns', 'Konecranes adopted a VR crane simulator in May 2026 to expand training capacity and cut equipment downtime. Packaging VR with equipment lets customers induct users without stopping the plant, and lets sales demo features around the clock.', 'Your ImmersiveXR builds from a customer''s CAD, scans or generative AI models. It covers shutdown, maintenance and full-system training. The page names no OEM client, so confirm one before writing a case. Your 2023 OEM induction article exists, so this is a refresh.', '{oem-training,short-insight,vr-simulation}'::text[], '[{"title": "ImmersiveXR for OEMs", "publisher": "Capital XR", "url": "https://capitalxr.com.au/immersivexr-for-oems"}, {"title": "VR market", "publisher": "Mordor Intelligence", "url": "https://www.mordorintelligence.com/industry-reports/virtual-reality-market"}, {"title": "Knowledge Base", "publisher": "Capital XR", "url": "https://capitalxr.com.au/thoughtleadership"}]'::jsonb, 1 from companies where slug = 'capitalxr-3tbkt1'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'cxr-03', 'short_insight', 'Defence XR Training: Plan the Device Fleet', 'Samsung added Android Enterprise to Galaxy XR, with Knox security and managed app deployment for training and manufacturing. Defence buyers need managed fleets, controlled updates and security review designed in from day one.', 'Your site cites nine years working with the Australian Defence Force and delivery in ten countries. It names no projects, so get approved detail before writing from it.', '{defence-training,short-insight,enterprise-xr}'::text[], '[{"title": "About", "publisher": "Capital XR", "url": "https://capitalxr.com.au/about-us"}, {"title": "Galaxy XR enterprise update", "publisher": "Samsung", "url": "https://news.samsung.com/global/samsung-galaxy-xr-evolves-work-in-the-ai-era-with-new-enterprise-capabilities-and-everyday-features"}]'::jsonb, 2 from companies where slug = 'capitalxr-3tbkt1'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
