-- Import for Cognitive3D (cognitive3d-qoy62b). Generated from clients/cognitive3d-qoy62b.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('cognitive3d-qoy62b', 'Cognitive3D', 'Tony', 'Tony', 'your eye tracking and analytics work, and the questions research teams ask before they trust XR session data', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'c3d-01', 'long_form', 'One Fixation Layer, Many Permission Models', 'Cognitive3D''s unified fixations system abstracts fixations across Vive Pro Eye, Tobii, Pupil Labs, AdHawk, FOVE and Qualcomm reference designs. Android XR is a separate example of the problem: it splits eye tracking into coarse and fine runtime permissions and calls the data sensitive personal information.', 'Your visionOS page says you use headset direction as a gaze proxy because Apple does not expose eye tracking to third-party developers. No page we opened says the fixations system runs on Android XR, so the article treats Android XR only as a permission model. No article on your site explains what a cross-device fixation layer preserves when one platform exposes eye data and another does not.', '{eye-tracking,long-form,company-reported}'::text[], '[{"title": "Unified fixations system", "publisher": "Cognitive3D", "url": "https://cognitive3d.com/blog/blog/cognitive3d-launches-unified-fixations-system/"}, {"title": "Apple Vision Pro", "publisher": "Cognitive3D", "url": "https://cognitive3d.com/blog/applevisionpro/"}, {"title": "Android XR eye tracking permissions", "publisher": "Android Developers", "url": "https://developer.android.com/develop/xr/openxr/extensions/XR_ANDROID_eye_tracking"}]'::jsonb, 0 from companies where slug = 'cognitive3d-qoy62b'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'c3d-02', 'short_insight', 'Raw Eye Data Stays Local, Outputs Do Not', 'Cognitive3D''s HarmonEyes integration adds four outputs: Mental Workload, Fatigue, Mental Readiness and Attention. The company says eye-tracking data stays on-device while model outputs enter the Cognitive3D session record, and initial availability is through the Unity SDK.', 'Your post gives no numbers or validation method and announces a demo at AWE USA, booth 929. No article on your site explains how the inferred states are computed, what leaves the headset and what an instructor should infer from the four outputs.', '{privacy-architecture,short-insight,company-reported}'::text[], '[{"title": "HarmonEyes partnership", "publisher": "Cognitive3D", "url": "https://cognitive3d.com/blog/harmoneyes-partner/"}, {"title": "Unified fixations system", "publisher": "Cognitive3D", "url": "https://cognitive3d.com/blog/blog/cognitive3d-launches-unified-fixations-system/"}, {"title": "About", "publisher": "Cognitive3D", "url": "https://cognitive3d.com/about/"}]'::jsonb, 1 from companies where slug = 'cognitive3d-qoy62b'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'c3d-03', 'short_insight', 'What 290 Million XR Minutes Cannot Show', 'Cognitive3D reports more than 290 million minutes of recorded XR sessions in an undated post that references its AWE USA 2026 talk, held June 15 to 18, 2026. Minute totals on its other pages cover different periods, so the article sets one definition.', 'Your post reports nearly 75% of users ending sessions within five minutes in one social VR app and an onboarding completion gain from 40% to 60% in an A/B test, with no client named. These are examples from individual applications, not rates across 290 million minutes. The post describes the test design only at a high level. No article on your site gives the sample, assignment, uncertainty or session-counting rules.', '{analytics-methods,short-insight,company-reported}'::text[], '[{"title": "290 Million Minutes", "publisher": "Cognitive3D", "url": "https://cognitive3d.com/blog/290-million-minutes/"}, {"title": "AWE USA 2026", "publisher": "AWE", "url": "https://www.awexr.com/usa-2026"}, {"title": "About", "publisher": "Cognitive3D", "url": "https://cognitive3d.com/about/"}]'::jsonb, 2 from companies where slug = 'cognitive3d-qoy62b'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
