-- Import for Emteq Labs (emteq-jqcnq1). Generated from clients/emteq-jqcnq1.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('emteq-jqcnq1', 'Emteq Labs', 'Steen', 'Steen', 'your OCO sensing and eating research, and the questions researchers ask before they put sensors on a face', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r3-37', 'short_insight', 'Face Sensing Without a Camera on the Face', 'Meta holds 94 percent of display-less AI glasses in H1 2026 using outward cameras and microphones, and an inward-facing camera is the privacy fight nobody wants. Reading facial movement optically at the skin is the alternative the category has not had to consider.', 'Your OCO optomyography sensors measure facial movement without cameras or electrodes, sampling across 4 to 30 mm, and your referenced research reports 93 percent expression classification (F1 0.90); the Sense product separately uses an outward camera for food logging. The honest piece states what those signals tell researchers reliably and what they should not be asked to infer, and you have published nothing in 2026.', '{emotion-sensing-eyewear,short-insight,sensor-spec}'::text[], '[{"title": "AI glasses shipments surged 263% in H1 2026", "publisher": "9to5Mac", "url": "https://9to5mac.com/2026/09/21/report-ai-glasses-shipments-surged-263-in-h1-2026-as-apple-prepares-to-enter-the-market/"}, {"title": "From Biometrics to Emotion", "publisher": "Emteq Labs", "url": "https://www.emteqlabs.com/blog/from-biometrics-to-emotion-engineering-the-future-of-smart-wearables"}, {"title": "Emteq''s Eyewear Detects Emotions", "publisher": "IEEE Spectrum", "url": "https://spectrum.ieee.org/glasses-health-tech"}]'::jsonb, 0 from companies where slug = 'emteq-jqcnq1'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r3-38', 'long_form', 'Detecting a Meal Is Not Knowing What Was Eaten', 'Purdue''s NIH-funded 200-person study (August 2026) exists because 24-hour recalls take 30 to 45 minutes a day and underreport calories by an estimated 5 to 15 percent; its device adds a camera triggered by chewing. Passive eating detection now has federal money behind it, and the boundary between detection and intake is the open question.', 'Your validation reports over 90 percent chewing detection and identification of 96 percent of self-reported eating episodes across 100-plus participants, and Bristol''s Consumer Lab is testing haptic feedback with OCOsense. You have written about eating detection already; the rigorous follow-up draws the line between chewing signals, eating episodes and nutritional estimates.', '{dietary-sensing,long-form,validation-proof}'::text[], '[{"title": "New technology captures eating habits in real time", "publisher": "Purdue HHS", "url": "https://www.purdue.edu/hhs/news/2026/08/new-technology-captures-eating-habits-in-real-time-to-advance-nutrition-research/"}, {"title": "Revolutionizing Dietary Health via Mindful Eating", "publisher": "Emteq Labs", "url": "https://www.emteqlabs.com/blog/revolutionizing-dietary-health-via-mindful-eating-and-real-time-data"}, {"title": "smart glasses eating project", "publisher": "University of Bristol Consumer Lab", "url": "https://consumer-lab.bristol.ac.uk/project/using-smart-glasses-to-track-and-manipulate-eating-in-the-real-world/"}]'::jsonb, 1 from companies where slug = 'emteq-jqcnq1'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r3-39', 'short_insight', 'Where Valence Ends and Diagnosis Begins', 'FDA''s January 2026 wellness guidance turns on intended use, not on a banned word. Facial-activity research can explore relationships with emotional state without turning a finding into a diagnostic claim, and the line has to be drawn deliberately.', 'Your referenced research includes arousal and valence work with adults with depression alongside the 93 percent expression result, and your 2024 launch cited 27 patents and 28 publications. The piece states where you draw that line in products and publications, reviewed by your regulatory lead before it ships.', '{wellness-regulation,short-insight,research-proof}'::text[], '[{"title": "General Wellness: Policy for Low Risk Devices", "publisher": "FDA", "url": "https://www.fda.gov/media/90652/download"}, {"title": "Research using Emteq devices", "publisher": "Emteq Labs", "url": "https://www.emteqlabs.com/research-using-emteq-labs-devices"}, {"title": "Emteq Labs Unveils Emotion-Sensing Eyewear", "publisher": "GlobeNewswire", "url": "https://www.globenewswire.com/news-release/2024/10/15/2963261/0/en/Emteq-Labs-Unveils-World-s-First-Emotion-Sensing-Eyewear.html"}]'::jsonb, 2 from companies where slug = 'emteq-jqcnq1'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
