-- Import for Epicore Biosystems (epicore-8wqf7e). Generated from clients/epicore-8wqf7e.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('epicore-8wqf7e', 'Epicore Biosystems', 'Roozbeh', 'Roozbeh', 'your hydration score and field notes, and the questions safety teams ask before they act on sweat data', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'epi-01', 'short_insight', 'What a Hydration Score Says About One Worker', 'Epicore launched a daily hydration score on June 9, 2026 built from sweat loss, sweating rate, sodium, skin temperature and motion data on a reusable armband. The release calls Epicore''s biowearable solutions clinically validated and gives no validation result, accuracy figure or user count for the new score.', 'Your release uses two names for the score, Hydration Readiness Score in the headline and Hydration Edge Score in the body. Its 28,000 injuries and $100 billion figures are market claims, not Epicore results. No article on your site explains which parts of the score come from one worker''s own measurements and which rely on comparisons or built-in assumptions.', '{hydration-scoring,short-insight,company-reported}'::text[], '[{"title": "Epicore launches hydration readiness score, June 9, 2026", "publisher": "PR Newswire", "url": "https://www.prnewswire.com/news-releases/epicore-biosystems-launches-first-hydration-readiness-score-for-proactive-health-insights-302795047.html"}, {"title": "Field notes", "publisher": "Epicore Biosystems", "url": "https://epicorebiosystems.com/field-notes/"}, {"title": "About", "publisher": "Epicore Biosystems", "url": "https://epicorebiosystems.com/about/"}]'::jsonb, 0 from companies where slug = 'epicore-8wqf7e'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'epi-02', 'short_insight', 'Collecting Sweat Across a Twelve-Hour Shift', 'Epicore''s September 9, 2026 field note by Dr. Ghaffari says access to sweat is the bottleneck, not its chemistry, and cites 12-hour wear, a claim we did not independently confirm. The post gives no accuracy data, and the June 9 release describes a reusable armband without single-use adhesive. The article covers sensor contact and measurement consistency across a shift.', 'Your seven most recent field notes cover personalized hydration, sweat as a biofluid, cognition and the World Cup, and none covers how the sweat-rate and sodium channel is calibrated. No article on your site explains what keeps measurements consistent when the same armband is worn, removed, cleaned and worn again.', '{sweat-sensing,short-insight,company-reported}'::text[], '[{"title": "Field notes", "publisher": "Epicore Biosystems", "url": "https://epicorebiosystems.com/field-notes/"}, {"title": "Epicore hydration score release", "publisher": "PR Newswire", "url": "https://www.prnewswire.com/news-releases/epicore-biosystems-launches-first-hydration-readiness-score-for-proactive-health-insights-302795047.html"}, {"title": "About", "publisher": "Epicore Biosystems", "url": "https://epicorebiosystems.com/about/"}]'::jsonb, 1 from companies where slug = 'epicore-8wqf7e'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'epi-03', 'long_form', 'Mapping a Daily Hydration Score to Heat Rules', 'OSHA renewed its heat National Emphasis Program on April 10, 2026 for five years, per OSHA''s release. The release does not address the federal heat rule, and we did not confirm its current status. The article states the enforcement program first and the rule second.', 'Your June 9, 2026 release frames a daily score for proactive health insights, and your September 10, 2026 field note applies sport-science protocols to heat stress. We found no 2026 measured armband result or customer deployment count. A hydration score does not by itself show compliance with an employer''s heat-safety duties, which may also depend on state rules. No article on your site explains where a daily score informs a safety team''s decisions and where other controls and records must carry the duty.', '{heat-regulation,long-form,primary-source}'::text[], '[{"title": "National Emphasis Program on heat renewed, April 10, 2026", "publisher": "OSHA", "url": "https://www.osha.gov/news/newsreleases/osha-national-news-release/20260410"}, {"title": "Epicore hydration score release", "publisher": "PR Newswire", "url": "https://www.prnewswire.com/news-releases/epicore-biosystems-launches-first-hydration-readiness-score-for-proactive-health-insights-302795047.html"}, {"title": "Field notes", "publisher": "Epicore Biosystems", "url": "https://epicorebiosystems.com/field-notes/"}]'::jsonb, 2 from companies where slug = 'epicore-8wqf7e'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
