-- Import for Fundamental XR (fundamentalxr-z5ufj4). Generated from clients/fundamentalxr-z5ufj4.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('fundamentalxr-z5ufj4', 'Fundamental XR', 'Richard', 'Richard', 'your haptic surgical training programs, and the questions faculty ask before simulator practice counts', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'fxr-01', 'long_form', 'From Logged Hours to Cataract Competence', 'Fundamental XR''s July 29, 2026 Orbis article reports that 13 first-year residents at Korle Bu in Ghana collectively logged more than 230 hours of cataract surgery simulation this year, and that faculty saw fewer wet-lab errors. The article gives no baseline, sample or method for the error change. Hours show practice, not competence.', 'Your article reports 22 partner institutions across Africa, Asia and South America, as a company and Orbis figure. Eyewire describes the program figures as program output, not a formal clinical study. No article on your site explains how simulator scores are checked against wet lab and operating room performance.', '{skill-transfer,long-form,company-reported}'::text[], '[{"title": "What happens when surgeons can fail safely first, July 29, 2026", "publisher": "Fundamental XR", "url": "https://www.fundamentalxr.com/news/what-happens-when-surgeons-can-fail-safely-first"}, {"title": "Home", "publisher": "Fundamental XR", "url": "https://www.fundamentalxr.com"}]'::jsonb, 0 from companies where slug = 'fundamentalxr-z5ufj4'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'fxr-02', 'short_insight', 'Five Simulator Kits Serving a Wider Network', 'Program reporting we opened lists five simulator kits in Rwanda, Ethiopia, Zambia and Ghana. Fundamental XR''s July 29, 2026 article confirms 22 partner institutions but gives no kit count, so the article does not claim five kits served all 22 sites. It asks how a small kit pool is shared.', 'The 2,700+ sessions and 1,100+ hours of surgical practice appear in secondary reporting attributed to the organizations, not in your July 29 article, and they are program-reported. The kit count and the institution count are not the same denominator. No article on your site explains how scheduling, maintenance and remote support work for shared kits.', '{program-logistics,short-insight,company-reported}'::text[], '[{"title": "What happens when surgeons can fail safely first, July 29, 2026", "publisher": "Fundamental XR", "url": "https://www.fundamentalxr.com/news/what-happens-when-surgeons-can-fail-safely-first"}, {"title": "Home", "publisher": "Fundamental XR", "url": "https://www.fundamentalxr.com"}]'::jsonb, 1 from companies where slug = 'fundamentalxr-z5ufj4'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'fxr-03', 'short_insight', 'Training Two Surgeons Together in Subretinal Surgery', 'Fundamental XR''s May 5, 2026 post says its HapticVR platform supports a two-person surgical configuration for Luxturna training, across 5 continents and 25+ countries. The post does not say how each surgeon is scored, so the article asks what the system can record about the pair.', 'Your post reports no outcome metrics and names no partners. No article on your site explains how the two roles are coordinated in the exercise or what the simulator records for each surgeon.', '{surgical-simulation,short-insight,company-reported}'::text[], '[{"title": "From Breakthrough Science to Surgical Readiness, May 5, 2026", "publisher": "Fundamental XR", "url": "https://www.fundamentalxr.com/news/from-breakthrough-science-to-surgical-readiness"}, {"title": "Home", "publisher": "Fundamental XR", "url": "https://www.fundamentalxr.com"}]'::jsonb, 2 from companies where slug = 'fundamentalxr-z5ufj4'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
