-- Import for Gravity Sketch (gravitysketch-nl01j2). Generated from clients/gravitysketch-nl01j2.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('gravitysketch-nl01j2', 'Gravity Sketch', 'Oluwaseyi', 'Oluwaseyi', 'your Donkervoort, Ford and DLR stories, and the questions design leads ask before they move reviews into VR', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-04', 'long_form', 'VR Mesh to Class A: The Conversion Step', 'Car programs are compressing toward two-year cycles, and the slowest handoff in exterior design is still getting a concept surface into a Class A tool. The problem is not that VR cannot export NURBS; it is that polygon data converted to NURBS patches is hard to edit afterward.', 'Your Donkervoort F22 story shows two handoffs: a mesh milled directly for verification, then the final model taken into Alias for Class A surfacing. Your export guide confirms native NURBS exports like-for-like while converted patches get tricky. No article on your site tells a surfacing lead when to mill a mesh, preserve native NURBS or rebuild downstream.', '{class-a-surfacing,long-form,customer-story}'::text[], '[{"title": "Designing the Donkervoort F22", "publisher": "Gravity Sketch", "url": "https://gravitysketch.com/resources/type/customer-stories/designing-the-donkervoort-f22/"}, {"title": "Export Best Practices", "publisher": "Gravity Sketch Help", "url": "https://help.gravitysketch.com/hc/en-us/articles/5902439321629-Export-Best-Practices"}, {"title": "Chinese Brands Got So Fast At Developing New Cars", "publisher": "Carscoops", "url": "https://www.carscoops.com/2026/09/chinese-automakers-should-slow-down-development/"}]'::jsonb, 0 from companies where slug = 'gravitysketch-nl01j2'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-05', 'short_insight', 'Milling Budgets Under 24-Month Car Programs', 'Renault shipped Twingo E-Tech in 21 months and Chinese OEMs run two-year cycles. Each full-scale milling pass is a line item that program timing no longer tolerates easily.', 'Donkervoort''s designer puts a milling at up to 40,000 EUR and says he would probably use one before sign-off after 1:1 VR evaluation; the F22 went from sketch to production in under two years. Ford''s Paul Wraith describes catching errors before milling. The piece is which decisions still deserve clay and which can be settled at full scale in VR.', '{automotive-design,short-insight,customer-story}'::text[], '[{"title": "Designing the Donkervoort F22", "publisher": "Gravity Sketch", "url": "https://gravitysketch.com/resources/type/customer-stories/designing-the-donkervoort-f22/"}, {"title": "Paul Wraith on Gravity Sketch at Ford Design", "publisher": "Gravity Sketch", "url": "https://gravitysketch.com/resources/type/customer-stories/paul-wraith-on-the-integration-of-gravity-sketch-into-ford-designs-process/"}, {"title": "Chinese Brands Got So Fast At Developing New Cars", "publisher": "Carscoops", "url": "https://www.carscoops.com/2026/09/chinese-automakers-should-slow-down-development/"}]'::jsonb, 1 from companies where slug = 'gravitysketch-nl01j2'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-06', 'short_insight', 'How DLR Brought First-Time VR Users Into Aircraft Design', 'Stakeholder reviews are moving into headsets, and the people in them are passengers, crew and executives, not designers. Your comfort guidance recommends a break after 45 to 60 minutes and dates from 2021.', 'DLR ran 18 two-hour workshops involving 65 passengers with no XR experience to validate cabin concepts at 1:1 scale, after a short grab, duplicate and undo introduction. The case study covers the intro; the facilitation plan, headset rotation and how much of each session was actually spent in VR are the missing article.', '{vr-usability,short-insight,customer-story}'::text[], '[{"title": "DLR cabin concept validation at 1:1 scale", "publisher": "Gravity Sketch", "url": "https://gravitysketch.com/resources/type/customer-stories/user-testing-in-vr-dlrs-approach-to-cabin-concept-validation-at-11-scale/"}, {"title": "Everything you need to know to work in VR comfortably", "publisher": "Gravity Sketch", "url": "https://gravitysketch.com/blog-post/articles/everything-you-need-to-know-to-work-in-vr-comfortably/"}, {"title": "Gravity Sketch 6.7", "publisher": "Gravity Sketch", "url": "https://gravitysketch.com/blog-post/updates/gravity-sketch-6-7/"}]'::jsonb, 2 from companies where slug = 'gravitysketch-nl01j2'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
