-- Import for Hadean (hadean-7d4vei). Generated from clients/hadean-7d4vei.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('hadean-7d4vei', 'Hadean', 'Craig', 'Craig', 'your dominAI, DIANA and Palantir work, and the questions defence teams ask before AI informs command', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'had-01', 'short_insight', 'How Multi-Vendor Sensor Data Gets Fused', 'The UK Defence Investment Plan published June 30, 2026 allocates nearly £7.3 billion over four years to the digital targeting web, per the Commons Library briefing. That is a budget line, not a Hadean contract. Hadean''s May 6, 2026 SCEPTRE event was a demonstration where dominAI ingested live feeds and generated courses of action within minutes, not an operational deployment.', 'Your news post describes the Trident Sprint 2 demonstration at the April 30 distinguished visitor day. The 50-day uncrewed endurance figure belongs to partner ACUA Ocean''s vessel and is not a Hadean result. No article on your site explains how tracks from several vendors are normalized before dominAI fuses them.', '{command-and-control,short-insight,demonstration}'::text[], '[{"title": "Defence Investment Plan briefing", "publisher": "House of Commons Library", "url": "https://commonslibrary.parliament.uk/research-briefings/cbp-10935/"}, {"title": "News", "publisher": "Hadean", "url": "https://hadean.com/news"}, {"title": "Hadean x Palantir", "publisher": "Hadean", "url": "https://hadean.com/hadean-x-palantir/"}]'::jsonb, 0 from companies where slug = 'hadean-7d4vei'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'had-02', 'long_form', 'Validating AI Wargaming Before It Informs Command', 'NATO named Hadean one of ten DIANA innovators on July 13, 2026, each receiving EUR 100,000 in contractual funding for integration and demonstration, with assessment expected by December 2026. Selection is a development pathway, not NATO-wide adoption or an operational result.', 'Your July 14, 2026 news post announces the selection. Your blog covers sovereignty, alliances and command and control strategy, and its listing shows nothing after February 27, 2026. No article on your site explains how an AI-assisted wargame is validated or what makes its outputs checkable.', '{wargame-validation,long-form,announcement}'::text[], '[{"title": "DIANA selects innovators, July 13, 2026", "publisher": "NATO", "url": "https://www.nato.int/en/news-and-events/articles/news/2026/07/13/natos-diana-selects-innovators-to-drive-decision-superiority-for-the-alliance"}, {"title": "News", "publisher": "Hadean", "url": "https://hadean.com/news"}]'::jsonb, 1 from companies where slug = 'hadean-7d4vei'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'had-03', 'short_insight', 'A Classified Pathway Is Not a Deployment', 'Hadean and Palantir announced on September 10, 2025 that wargaming, command and control and training products would run on Foundry, with availability in classified MoD environments expected within months. Hadean''s Palantir page, last modified February 20, 2026, describes a pathway into those environments. We found no public confirmation of deployment, which is not proof that none occurred.', 'Your March 11, 2026 bridge round post cites the £20m enterprise agreement as past execution, and the December 4, 2024 announcement calls it an agreement worth up to £20 million, a ceiling and not booked revenue. No article on your site explains what changes in security, validation and data distribution when a training simulation informs a live decision.', '{secure-deployment,short-insight,announcement}'::text[], '[{"title": "Palantir and Hadean partner", "publisher": "Hadean", "url": "https://hadean.com/news/palantir-and-hadean-partner-to-bring-a-suite-of-simulation-and-ai-products-across-the-uk-armed-forces/"}, {"title": "Hadean x Palantir", "publisher": "Hadean", "url": "https://hadean.com/hadean-x-palantir/"}, {"title": "Acceleration funding, March 11, 2026", "publisher": "Hadean", "url": "https://hadean.com/news/hadean-secures-acceleration-funding-to-fuel-ambitions-as-the-uks-next-defence-dual-use-tech-unicorn/"}, {"title": "Enterprise Lite agreement with the UK MoD", "publisher": "Hadean", "url": "https://hadean.com/news/hadean-signs-enterprise-lite-agreement-with-the-uk-ministry-of-defence/"}]'::jsonb, 2 from companies where slug = 'hadean-7d4vei'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
