-- Import for Hexoskin (hexoskin-ysz3ey). Generated from clients/hexoskin-ysz3ey.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('hexoskin-ysz3ey', 'Hexoskin', 'Pierre-Alexandre', 'Pierre-Alexandre', 'your 510(k) clearance and research record, and the questions clinical leads ask before they trust a wearable', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r3-34', 'short_insight', 'Respiratory Monitoring Is the Uncleared Frontier', 'FDA''s January 2026 wellness guidance turns on intended use: a wellness wearable may report a breathing-related metric, and a device making clinical claims needs clearance. Continuous respiratory monitoring for care is the harder path, and you have taken it.', 'Your Hexoskin Medical System received 510(k) clearance in November 2025 to record, store and analyse ECG, respiratory and activity signals in ambulatory patients, using dual-channel respiratory inductance plethysmography. Your 2026 blog is conference announcements; the piece on what changes in signals, evidence and intended use when breathing data enters clinical care is unwritten.', '{medical-wearables,short-insight,fda-proof}'::text[], '[{"title": "Hexoskin Medical System Receives FDA 510(k) Clearance", "publisher": "Hexoskin", "url": "https://hexoskin.com/blogs/news/a-breakthrough-in-remote-care-hexoskin-medical-system-receives-fda-510k-clearance-for-long-term-ecg-and-respiratory-monitoring"}, {"title": "General Wellness: Policy for Low Risk Devices", "publisher": "FDA", "url": "https://www.fda.gov/media/90652/download"}, {"title": "Jean-Pierre Desmarais joins board (sensor spec)", "publisher": "Hexoskin", "url": "https://hexoskin.com/blogs/news/medtech-veteran-and-serial-entrepreneur-jean-pierre-desmarais-joins-hexoskins-board-of-directors"}]'::jsonb, 0 from companies where slug = 'hexoskin-ysz3ey'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r3-35', 'short_insight', 'Short-Window RPM Changes What a Garment Has to Do', 'CPT 99445, effective January 1 2026, covers device supply with recordings on 2 to 15 days in a 30-day period where the old floor was 16 days. A garment designed for long studies now also has to serve a short clinical episode well.', 'Your homepage claims 36-plus hours of battery and 100-plus days of recording, built around research deployments. The article works through what a shorter episode asks of setup, wear time, usable data and follow-up, without assuming every short deployment is billable.', '{remote-patient-monitoring,short-insight,product-spec}'::text[], '[{"title": "2026 Remote Patient Monitoring CPT Codes", "publisher": "Prevounce", "url": "https://blog.prevounce.com/2026-remote-patient-monitoring-cpt-codes-whats-new-and-what-to-know"}, {"title": "homepage", "publisher": "Hexoskin", "url": "https://www.hexoskin.com"}, {"title": "FDA 510(k) post", "publisher": "Hexoskin", "url": "https://hexoskin.com/blogs/news/a-breakthrough-in-remote-care-hexoskin-medical-system-receives-fda-510k-clearance-for-long-term-ecg-and-respiratory-monitoring"}]'::jsonb, 1 from companies where slug = 'hexoskin-ysz3ey'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r3-36', 'long_form', 'A Cleared Sensor Is Not a Cleared Endpoint', 'Pharma sponsors want digital biomarkers from wearables, and recent papers derive seizure forecasting, anxiety detection and metabolic rate from the same ECG and breathing streams. A cleared system collects dependable signals; each derived measure still has to be validated for its own indication.', 'Your publications page cites over 250 scientific publications across the platform, and you pitched cardiology, respiratory, nervous system and rare disease at BIO 2026 and the Basel digital biomarkers summit. The piece is how a sponsor''s clinical lead should evaluate a proposed wearable-derived measure, and it would be forwarded.', '{digital-biomarkers,long-form,publication-proof}'::text[], '[{"title": "Scientific Publications", "publisher": "Hexoskin", "url": "https://hexoskin.com/pages/scientific-publications"}, {"title": "BIO 2026", "publisher": "Hexoskin", "url": "https://hexoskin.com/blogs/news/hexoskin-in-san-diego-for-bio-2026"}, {"title": "FDA 510(k) post", "publisher": "Hexoskin", "url": "https://hexoskin.com/blogs/news/a-breakthrough-in-remote-care-hexoskin-medical-system-receives-fda-510k-clearance-for-long-term-ecg-and-respiratory-monitoring"}]'::jsonb, 2 from companies where slug = 'hexoskin-ysz3ey'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
