-- Import for HTX Labs (htxlabs-mzgfv4). Generated from clients/htxlabs-mzgfv4.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('htxlabs-mzgfv4', 'HTX Labs', 'Scott', 'Scott', 'your EMPACT work and the questions training commands ask before they trust readiness data', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'htx-01', 'short_insight', 'Disconnected Training Needs a Sync Contract', 'HTX Labs described EMPACT on July 6, 2026 as a Cloud-to-Edge system for disconnected, low-bandwidth, contested environments that syncs content updates and performance uploads when connectivity allows. The release does not say what happens when a transfer stops mid-sync, so the article is built from an interview.', 'Your July 6, 2026 release says the system is device and content agnostic and describes no conflict handling. Your March 25, 2026 post on fragmented content covers discovery and sharing, not synchronization. No article on your site explains how the edge resolves conflicting changes or a failed transfer after a disconnect.', '{edge-sync,short-insight,company-reported}'::text[], '[{"title": "HTX Labs establishes EMPACT as a mission readiness system", "publisher": "EIN Presswire", "url": "https://www.einpresswire.com/article/923307261/htx-labs-establishes-empact-as-a-mission-readiness-system"}, {"title": "News", "publisher": "HTX Labs", "url": "https://www.htxlabs.com/news"}, {"title": "Company", "publisher": "HTX Labs", "url": "https://www.htxlabs.com/company"}]'::jsonb, 0 from companies where slug = 'htxlabs-mzgfv4'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'htx-02', 'long_form', 'Contract Vehicles Do Not Measure Readiness', 'HTX Labs announced a May 2026 extension of its DoD-wide IDIQ through September 2028. An IDIQ is a contracting route, not a count of orders or evidence of training outcomes. Readiness only means something if the performance data under each order is comparable.', 'Your extension post describes onboarding within 48 hours through a Contracting Officer, which is a company claim. Your May 16, 2025 Yet Analytics partnership integrates xAPI performance tracking for USAF immersive training, with no numbers. No article on your site explains which performance records an xAPI feed must carry before a commander can compare units.', '{readiness-data,long-form,company-reported}'::text[], '[{"title": "News", "publisher": "HTX Labs", "url": "https://www.htxlabs.com/news"}, {"title": "EMPACT release", "publisher": "EIN Presswire", "url": "https://www.einpresswire.com/article/923307261/htx-labs-establishes-empact-as-a-mission-readiness-system"}, {"title": "Company", "publisher": "HTX Labs", "url": "https://www.htxlabs.com/company"}]'::jsonb, 1 from companies where slug = 'htxlabs-mzgfv4'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'htx-03', 'short_insight', 'Accreditation Is a Ladder, Not a Badge', 'HTX Labs said on July 6, 2026 that EMPACT holds an IL4 ATO on NIPRNet and that IL5 is in progress. Both are company claims, and no authorization record was opened. The article is built from an interview with HTX''s security and accreditation team.', 'Your homepage also claims an IL-4 ATO on AFNET and CMMC compliance, undated, which may describe a different boundary. Your May 28, 2025 cybersecurity post names no standards. No article on your site explains the accreditation path HTX has followed for EMPACT or what changes between IL4 and IL5.', '{accreditation,short-insight,company-reported}'::text[], '[{"title": "EMPACT release", "publisher": "EIN Presswire", "url": "https://www.einpresswire.com/article/923307261/htx-labs-establishes-empact-as-a-mission-readiness-system"}, {"title": "Home", "publisher": "HTX Labs", "url": "https://www.htxlabs.com"}, {"title": "News", "publisher": "HTX Labs", "url": "https://www.htxlabs.com/news"}]'::jsonb, 2 from companies where slug = 'htxlabs-mzgfv4'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
