-- Import for JigSpace (jigspace-v8fwd2). Generated from clients/jigspace-v8fwd2.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('jigspace-v8fwd2', 'JigSpace', 'Zac', 'Zac', 'your Vision Pro, iPad and web releases, and the questions sales and service teams ask before they put a product in a headset', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'jig-01', 'short_insight', 'Demo Throughput Is a Presenter Problem', 'Provisur ran over 400 demos at IFFA 2025 on Vision Pro and iPad, per JigSpace''s June 2, 2025 case study. JigSpace''s September 18, 2025 post, written after the show, names the constraint as a presenter who cannot see what the viewer sees.', 'Your Provisur case study describes the work as a pilot with expansion planned. Your remote-app post models 3 to 6 demos per hour for two devices over an 8-hour event, which is your own modeled estimate and not customer data. The 400 demos predate the remote app and are not its result. No article on your site explains how a presenter team plans and runs an event day end to end when the guest is inside the headset.', '{demo-throughput,short-insight,company-reported}'::text[], '[{"title": "Provisur at IFFA 2025", "publisher": "JigSpace", "url": "https://www.jig.com/case-studies/provisur-jigspace-leading-with-innovation-at-iffa-2025"}, {"title": "Why we built a remote control for Apple Vision Pro", "publisher": "JigSpace", "url": "https://www.jig.com/blog/why-we-built-a-remote-control-for-apple-vision-pro"}, {"title": "What''s new", "publisher": "JigSpace", "url": "https://www.jig.com/whats-new"}]'::jsonb, 0 from companies where slug = 'jigspace-v8fwd2'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'jig-02', 'short_insight', 'What a Spatial Vendor Does After Vision Pro', 'MacRumors reported on April 29, 2026, citing no named source, that Apple stopped Vision Pro development. That is an unconfirmed report, and we did not open an Apple statement. JigSpace reported 100,000 Vision Pro users in December 2025 and kept shipping Vision releases through 1.18 on August 10, 2026.', 'Your 2025 year in review says the 100,000 are users, not downloads or signups, with over 25,000 hours logged. Your what''s-new page lists a web browser performance gain of over 3x in version 3.45 on August 17, 2026. These are company claims. No article on your site explains what stays portable across Vision Pro, iPad and web when a headset target changes.', '{platform-risk,short-insight,company-reported}'::text[], '[{"title": "Apple Vision Pro report, April 29, 2026", "publisher": "MacRumors", "url": "https://www.macrumors.com/2026/04/29/apple-vision-pro-m5-flop/"}, {"title": "2025 Year in Review", "publisher": "JigSpace", "url": "https://www.jig.com/blog/2025-year-in-review"}, {"title": "What''s new", "publisher": "JigSpace", "url": "https://www.jig.com/whats-new"}]'::jsonb, 1 from companies where slug = 'jigspace-v8fwd2'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'jig-03', 'long_form', 'CAD Files Are Not Render Ready', 'JigSpace shipped CAD optimization with model merging and optional geometry decimation in version 3.46 on September 16, 2026. The article explains why manufacturing geometry needs reduction before it presents well on a headset.', 'Your IKN case study describes a live spare-parts workflow built from CAD-derived 3D models, with IKN''s own quote on fewer part identification errors and faster quoting, and no measured reduction. Your what''s-new page lists Vision 1.17 loading Jigs approximately 25 to 50 percent faster, a separate earlier release and not a result of the CAD controls. No article on your site explains how decimation and merging choices change what a technician can still identify on a part.', '{cad-pipeline,long-form,published-result}'::text[], '[{"title": "What''s new", "publisher": "JigSpace", "url": "https://www.jig.com/whats-new"}, {"title": "IKN spare part selection", "publisher": "JigSpace", "url": "https://www.jig.com/case-studies/how-ikn-is-transforming-spare-part-selection-with-spatial-computing"}, {"title": "2025 Year in Review", "publisher": "JigSpace", "url": "https://www.jig.com/blog/2025-year-in-review"}]'::jsonb, 2 from companies where slug = 'jigspace-v8fwd2'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
