-- Import for ManageXR (managexr-jzghdc). Generated from clients/managexr-jzghdc.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('managexr-jzghdc', 'ManageXR', 'Luke', 'Luke', 'your Rooms and fleet work, and the questions IT teams ask before they run headsets at scale', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'mxr-01', 'long_form', 'Why Headset Streaming Fails at the Firewall', 'ManageXR''s July 10, 2026 post reports Rooms private beta streaming uptime rising from about 40% to 81.6% on average, across 55 organizations, 400+ Rooms and 1,300+ headsets. A K-12 facilitator quoted in the same post described a school firewall problem affecting 1 in 50 devices.', 'Your post names blocked endpoints, firmware bugs, casting restrictions and reconnect failures as causes and describes a network test. Its headline claims a 3x usage increase, and the body shows no calculation. Your network guide recommends 200 Mbps minimum and 5GHz. No article on your site walks an IT team through telling a blocked endpoint from a firmware, casting or reconnection fault.', '{network-reliability,long-form,company-reported}'::text[], '[{"title": "How we created a tool that increased VR usage by 3x", "publisher": "ManageXR", "url": "https://www.managexr.com/blog/how-we-created-a-tool-that-increased-vr-usage-by-3x"}, {"title": "How MDI uses Rooms", "publisher": "ManageXR", "url": "https://www.managexr.com/customer-stories/how-mdi-uses-rooms-to-run-vr-career-training-for-people-with-disabilities"}]'::jsonb, 0 from companies where slug = 'managexr-jzghdc'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'mxr-02', 'short_insight', 'What a Legacy Quest Fleet Loses', 'Meta''s support page says Horizon managed services stopped being available for purchase on February 20, 2026. UploadVR reports commercial Quest SKU sales ended the same day and that support for existing customers runs to January 4, 2030. The article tells a fleet owner what to check before choosing the next device-management path.', 'Your January 28, 2026 post on Meta HMS explains enrollment and predates the February 20 cutoff, so it does not show that purchasing is open. Your March 2025 firmware post covers update policy. No article on your site defines what a specific legacy headset model loses on a named feature.', '{fleet-lifecycle,short-insight,primary-source}'::text[], '[{"title": "Update to Meta Horizon managed services", "publisher": "Meta", "url": "https://work.meta.com/help/1964851097790493"}, {"title": "Meta is shutting down its Quest for Business program", "publisher": "UploadVR", "url": "https://www.uploadvr.com/meta-is-shutting-down-its-quest-for-business-program/"}]'::jsonb, 1 from companies where slug = 'managexr-jzghdc'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'mxr-03', 'short_insight', 'Rooms Replaces Per-Headset Casting in Job Training', 'MDI runs VR career training for people with disabilities, manages 46 active headsets and reported saving time by no longer casting each headset individually. Rooms supports up to 30 headsets per Room, and the facilitator adds the headsets she brings to each event.', 'Your MDI story reports 640+ Unified Work participants since 2023 and 50+ career simulations, as reported by ManageXR. The time saving is the facilitator''s qualitative report with no measured figure. Your beta post separately reports 400+ Rooms started. No article on your site explains how a facilitator decides which headsets to bring and how an event day runs in Rooms.', '{fleet-management,short-insight,published-result}'::text[], '[{"title": "How MDI uses Rooms", "publisher": "ManageXR", "url": "https://www.managexr.com/customer-stories/how-mdi-uses-rooms-to-run-vr-career-training-for-people-with-disabilities"}, {"title": "How we created a tool that increased VR usage by 3x", "publisher": "ManageXR", "url": "https://www.managexr.com/blog/how-we-created-a-tool-that-increased-vr-usage-by-3x"}]'::jsonb, 2 from companies where slug = 'managexr-jzghdc'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
