-- Import for Mentra (mentra-s6jur0). Generated from clients/mentra-s6jur0.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('mentra-s6jur0', 'Mentra', 'Cayden', 'Cayden', 'your MentraOS work and the questions developers ask before they build for smart glasses', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-01', 'short_insight', 'Why the App Runtime Moved to the Phone', 'Meta opened Ray-Ban Display to third-party apps in May 2026 but runs them on the phone, not the glasses. Mentra reached the same architecture from the open-source side, and its own account says latency and ownership forced the move.', 'Your June 2026 roadmap post describes the glasses to phone to cloud relay to developer app path and puts a button response at hundreds of milliseconds even in a good case; Mentra 3.0 (August 2026) moved every miniapp onto the phone with local STT and TTS models for when the connection drops. That is your own measurement, not a benchmark, and the article should say so.', '{smart-glasses-architecture,short-insight,roadmap-proof}'::text[], '[{"title": "Mentra Roadmap Update: Moving to Miniapps on the Phone", "publisher": "Mentra", "url": "https://mentraglass.com/blogs/blog/mentra-roadmap-update-moving-to-miniapps-on-the-phone"}, {"title": "Mentra 3.0", "publisher": "Mentra", "url": "https://mentraglass.com/blogs/blog/mentra-3-0-local-miniapps-full-user-control-and-enterprise-smart-glasses"}, {"title": "Meta Opens Ray-Ban Display Glasses to Third-Party Developers", "publisher": "gHacks", "url": "https://www.ghacks.net/2026/05/18/meta-opens-ray-ban-display-glasses-to-third-party-developers-through-wearables-toolkit/"}]'::jsonb, 0 from companies where slug = 'mentra-s6jur0'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-02', 'short_insight', 'Streaming Heat Is the Real Battery Ceiling', 'Meta says third-party apps cannot run on its glasses because of compute, thermal and battery limits. Your build log is the only public account of what that limit looks like on a bench.', 'Making Mentra Live (December 2025) names the original MTK6765, says high-quality streaming overheated it after 15-plus minutes, and describes the MTK8766 upgrade and separating the WiFi chip from the processor. The product page rates 40-plus minutes of livestreaming and 10-plus hours of mixed use, two different use profiles, and the piece is what you changed in the board and video pipeline between them.', '{wearable-thermals,short-insight,hardware-proof}'::text[], '[{"title": "Making Mentra Live", "publisher": "Mentra", "url": "https://mentraglass.com/blogs/blog/making-mentra-live"}, {"title": "Mentra Live product page", "publisher": "Mentra", "url": "https://mentraglass.com/live"}, {"title": "New Meta Developer Tool Enables Third-parties to Bring Apps to its Smart Glasses", "publisher": "Road to VR", "url": "https://roadtovr.com/meta-ray-ban-smart-glasses-third-party-app-sdk-device-access-toolkit/"}]'::jsonb, 1 from companies where slug = 'mentra-s6jur0'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-03', 'linkedin_post', 'One Vendor Ships Two Thirds of XR Devices', 'IDC put Meta at 68.7 percent of Q2 2026 shipments across its combined XR headset and glasses tracker, and Meta''s developer program is a preview with no stated review process. An open OS is only an argument if it runs on hardware people can buy.', 'MentraOS is Apache 2.0, supports Mentra Live, Even Realities G1 and G2 and Vuzix Z100, and your first 1,000-unit batch sold out in under a month. Your August post makes the open-platform case in general terms; the specific piece is what an open runtime lets an enterprise control across those devices.', '{open-source-hardware,linkedin-post,developer-proof}'::text[], '[{"title": "Smart Glasses Growth Cools to 35% as Meta Doubles Down on Distribution", "publisher": "IDC", "url": "https://www.idc.com/resource-center/blog/smart-glasses-growth-cools-to-35-as-meta-doubles-down-on-distribution/"}, {"title": "MentraOS on GitHub", "publisher": "Mentra-Community", "url": "https://github.com/Mentra-Community/MentraOS"}, {"title": "Batch 1 Sold Out", "publisher": "Mentra", "url": "https://mentraglass.com/blogs/blog/mentra-live-featured-in-engadget-gizmodo-new-york-post-and-more"}]'::jsonb, 2 from companies where slug = 'mentra-s6jur0'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
