-- Import for Neurable (neurable-uyhtot). Generated from clients/neurable-uyhtot.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('neurable-uyhtot', 'Neurable', 'Adam', 'Adam', 'your Neurable One launch and OEM platform, and the questions buyers ask before they wear EEG', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'neu-01', 'long_form', 'What Signal Quality Takes in Ear Pad EEG', 'Neurable announced Neurable One on October 1, 2026 at $499, available in the United States, with 12 EEG sensors in the ear pads. Engadget reports battery life falls from 22 hours of audio to 12 hours with EEG active, and an independent researcher told IEEE Spectrum that dry EEG is typically noisy.', 'Your explainer on EEG in headphones says the signal is less comprehensive than a clinical cap and gives no accuracy or latency numbers. Your release cites Air Force and Mayo Clinic validation of the broader platform, with no study details for Neurable One''s scores. No article on your site explains how hair, skin contact, fit and movement change the signal and what supports the score a wearer sees.', '{eeg-signal-quality,long-form,company-reported}'::text[], '[{"title": "Neurable launches Neurable One, October 1, 2026", "publisher": "Business Wire", "url": "https://www.businesswire.com/news/home/20261001624775/en/"}, {"title": "Neurable One", "publisher": "Engadget", "url": "https://www.engadget.com/2271652/neurable-one-eeg-headphones/"}, {"title": "EEG headphones", "publisher": "IEEE Spectrum", "url": "https://spectrum.ieee.org/eeg-headphones-neurable-one"}]'::jsonb, 0 from companies where slug = 'neurable-uyhtot'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'neu-02', 'short_insight', 'Brain Data Banking Meets Neural Data Law', 'Neurable''s release says Brain Data Banking records and stores brain activity whenever Neurable One is worn with the app open, creating a continuous history. Connecticut amended its data privacy act to add neural data to sensitive data. Whether it applies to Neurable, and which dates apply, are open, so the article cites statute text and not a summary.', 'Your launch release lists Brain Data Banking as a feature and states no retention or deletion terms. No article on your site explains what you store, for how long, how a user deletes it and how consent works across states that treat neural data as sensitive.', '{neural-data-privacy,short-insight,secondary-source}'::text[], '[{"title": "Neurable launches Neurable One, October 1, 2026", "publisher": "Business Wire", "url": "https://www.businesswire.com/news/home/20261001624775/en/"}, {"title": "Connecticut amends the Connecticut Data Privacy Act", "publisher": "National Law Review", "url": "https://natlawreview.com/article/connecticut-amends-connecticut-data-privacy-act"}, {"title": "US states build patchwork of neural data privacy laws", "publisher": "Inside BCI", "url": "https://insidebci.com/policy/2026-04-03-us-states-build-patchwork-of-neural-data-privacy-laws-as-bci-market-accelerates/"}]'::jsonb, 1 from companies where slug = 'neurable-uyhtot'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'neu-03', 'short_insight', 'One Brain Signal Pipeline, Many Form Factors', 'Neurable announced its OEM licensing platform on April 28, 2026, naming HP''s HyperX, MeSpace, iMotions and the U.S. Air Force Research Laboratory in different collaborative roles. The HyperX gaming headset was a concept-stage collaboration announced January 5, 2026, not a shipping product. Neurable One, announced October 1, 2026, is Neurable''s own consumer product.', 'Your April 27, 2026 OEM post sizes the market with unsourced figures and names no partners. No article on your site explains how one signal pipeline is tuned across earbuds, headphones and a gaming headset.', '{oem-licensing,short-insight,announcement}'::text[], '[{"title": "Neurable open for business, April 28, 2026", "publisher": "Business Wire", "url": "https://www.businesswire.com/news/home/20260428101416/en/Neurable-Open-for-Business-Scaling-Neurotechnology-Adoption-Through-Global-OEM-Integration"}, {"title": "HyperX collaboration", "publisher": "Neurable", "url": "https://www.neurable.com/news/neurable-introduces-neurotechnology-powered-gaming-wearable-headset-with-hyperx"}, {"title": "Neurable launches Neurable One, October 1, 2026", "publisher": "Business Wire", "url": "https://www.businesswire.com/news/home/20261001624775/en/"}]'::jsonb, 2 from companies where slug = 'neurable-uyhtot'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
