-- Import for Next World XR (nextworld-zpf50v). Generated from clients/nextworld-zpf50v.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('nextworld-zpf50v', 'Next World XR', 'Srividhya', 'Srividhya', 'your VR training analytics and the questions safety managers ask before they trust a VR certificate', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-07', 'long_form', 'Measuring Transfer, Not Completion', 'A March 2026 Scientific Reports study compared VR-trained substation workers against observations at a real site, and the field is starting to ask for that kind of evidence instead of completion rates. Your LMS already captures the inputs; the measurement guide is missing.', 'Your analytics page logs actions, decisions, accuracy and timing per trainee, while your Komatsu case reports a potential 55.13 percent time-efficiency saving per class for the 2022 cohort, a throughput figure. The article is how to turn logged decisions into a transfer measure a safety manager trusts.', '{training-measurement,long-form,lms-proof}'::text[], '[{"title": "Virtual reality to enhance risk management and safety in electrical substations", "publisher": "Nature Scientific Reports", "url": "https://www.nature.com/articles/s41598-026-35534-1"}, {"title": "VR Training Analytics", "publisher": "Next World XR", "url": "https://www.nextworldxr.com/vr-training-analytics"}, {"title": "Komatsu case study", "publisher": "Next World XR", "url": "https://www.nextworldxr.com/case-studies/komatsu"}]'::jsonb, 0 from companies where slug = 'nextworld-zpf50v'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-08', 'short_insight', 'What a VR Training Record Should Contain', 'WA mining statutory role holders face new competency and examination criteria from March 30 2026. A certificate from a VR LMS is only evidence if an assessor can see what was tested, how and when.', 'Your LMS issues certificates and exports data in multiple formats to a client LMS but names no SCORM or xAPI standard. The piece defines the fields a defensible record needs and where exports fall short.', '{training-compliance,short-insight,lms-proof}'::text[], '[{"title": "WHS Regulatory Updates Australia January 2026", "publisher": "Action OHS Consulting", "url": "https://www.actionohs.com.au/whs-regulatory-updates-australia-january-2026/"}, {"title": "FAQ", "publisher": "Next World XR", "url": "https://www.nextworldxr.com/faq"}, {"title": "VR Training Analytics", "publisher": "Next World XR", "url": "https://www.nextworldxr.com/vr-training-analytics"}]'::jsonb, 1 from companies where slug = 'nextworld-zpf50v'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-09', 'short_insight', 'Headset Fleets After Quest for Business', 'Meta stopped selling commercial Quest SKUs and new managed-services subscriptions on February 20 2026, with existing customers supported to January 2030. Any fleet standing up now is consumer hardware plus third-party MDM.', 'Your pricing page lists seven supported headsets across Meta and Pico while your FAQ names only two Pico devices, and offline mode is gated to the top tier. A fleet-ops guide for remote sites would resolve the inconsistency and answer the first question a mine site IT lead asks.', '{vr-fleet-management,short-insight,platform-shift}'::text[], '[{"title": "Meta Quest for Business Ends: What It Means for VR Training", "publisher": "Skillsive", "url": "https://www.skillsive.com/blog/meta-quest-for-business-ends-what-it-means-for-vr-training"}, {"title": "Pricing", "publisher": "Next World XR", "url": "https://www.nextworldxr.com/vr-training-pricing"}, {"title": "FAQ", "publisher": "Next World XR", "url": "https://www.nextworldxr.com/faq"}]'::jsonb, 2 from companies where slug = 'nextworld-zpf50v'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
