-- Import for Next World XR (nextworld-zpf50v). Generated from clients/nextworld-zpf50v.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('nextworld-zpf50v', 'Next World XR', 'Hayden', 'Hayden', 'your VR training analytics and the questions safety managers ask before they trust a VR certificate', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-07', 'long_form', 'Measuring Transfer, Not Completion', 'A March 2026 Scientific Reports study compared VR-trained substation workers against observations at a real site, and the field is starting to ask for that kind of evidence instead of completion rates. Your LMS already captures the inputs; the follow-up design is missing.', 'Your analytics page logs actions, decisions, accuracy and timing per trainee, while your Komatsu case reports a potential 55.13 percent time-efficiency saving per class for the 2022 cohort, a throughput figure. Logged decisions become a transfer measure only with later on-site assessment, and the article is how a safety manager designs that step.', '{training-measurement,long-form,lms-proof}'::text[], '[{"title": "Virtual reality to enhance risk management and safety in electrical substations", "publisher": "Nature Scientific Reports", "url": "https://www.nature.com/articles/s41598-026-35534-1"}, {"title": "VR Training Analytics", "publisher": "Next World XR", "url": "https://www.nextworldxr.com/vr-training-analytics"}, {"title": "Komatsu case study", "publisher": "Next World XR", "url": "https://www.nextworldxr.com/case-studies/komatsu"}]'::jsonb, 0 from companies where slug = 'nextworld-zpf50v'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-08', 'short_insight', 'Where a VR Record Sits in the Evidence Trail', 'WorkSafe WA''s transition for mine statutory positions ended March 30 2026, and appointees must meet role-specific criteria including examinations. A VR session is not that evidence, and your own FAQ says so.', 'Your FAQ states the platform cannot be used solely to certify someone in a course; it supplements learning or records refresher completion, and exports data in multiple formats without naming SCORM or xAPI. The piece defines what a VR record can show (what was practiced, how the learner responded) and where it fits inside a wider assessment.', '{training-compliance,short-insight,lms-proof}'::text[], '[{"title": "WorkSafe extends transition period for mines statutory positions", "publisher": "WorkSafe WA", "url": "https://www.worksafe.wa.gov.au/announcements/worksafe-extends-transition-period-mines-statutory-positions-0"}, {"title": "FAQ", "publisher": "Next World XR", "url": "https://www.nextworldxr.com/faq"}, {"title": "VR Training Analytics", "publisher": "Next World XR", "url": "https://www.nextworldxr.com/vr-training-analytics"}]'::jsonb, 1 from companies where slug = 'nextworld-zpf50v'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-09', 'short_insight', 'Headset Fleets After Quest for Business', 'Meta stopped selling commercial Quest SKUs and new managed-services subscriptions on February 20 2026, with existing Horizon Managed Services customers supported to January 4 2030. Everyone else standing up a fleet now is on consumer hardware plus third-party MDM.', 'Your pricing page lists seven compatible headsets, your FAQ names two Pico models for bring-your-own hardware, and offline mode appears as an Unlimited-tier feature while the FAQ says downloaded courses run without WiFi. A mine-site buyer needs those three answers in one place, and reconciling them is the article.', '{vr-fleet-management,short-insight,platform-shift}'::text[], '[{"title": "An update on Meta for Work", "publisher": "Meta for Work", "url": "https://work.meta.com/help/1964851097790493"}, {"title": "Pricing", "publisher": "Next World XR", "url": "https://www.nextworldxr.com/vr-training-pricing"}, {"title": "FAQ", "publisher": "Next World XR", "url": "https://www.nextworldxr.com/faq"}]'::jsonb, 2 from companies where slug = 'nextworld-zpf50v'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
