-- Import for Operator XR (operatorxr-mjmmet). Generated from clients/operatorxr-mjmmet.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('operatorxr-mjmmet', 'Operator XR', 'Wayne', 'Wayne', 'your Texas DPS and Interceptor work, and the questions agencies ask before they buy VR training', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r3-46', 'long_form', 'Offline VR Is the Real Procurement Requirement', 'Texas DPS selected OP-2 in August 2025 for a statewide deployment, and agency IT reviews turn heavily on connectivity, updates and where training data lives. Running multi-user tracked scenarios with real-weapon recoil on standalone headsets is what makes those answers easy.', 'OP-2 carries its own offline claims and shipped to Texas DPS on an initial AUD 4.3M order, up to AUD 5.71M with options; Interceptor, a separate product, runs with no backpack PC, no external tracking, no WiFi, at about 23 kg per two users. Your insights posts cover growth and events; the offline-architecture piece is the one a procurement officer forwards.', '{standalone-vr,long-form,contract-proof}'::text[], '[{"title": "Operator XR $5.71M Texas contract", "publisher": "xReality Group", "url": "https://xrgroup.com.au/news/operatorxr-5-71m-texas-contract/"}, {"title": "Operator XR Launches Interceptor", "publisher": "iTWire", "url": "https://itwire.com/it-people-news/education/operator-xr-launches-interceptor-purpose-built-c-suas-training-system.html"}, {"title": "Company spotlight Operator XR", "publisher": "Police1", "url": "https://www.police1.com/company-spotlight-operator-xr-delivers-immersive-vr-police-training-for-high-risk-decision-making"}]'::jsonb, 0 from companies where slug = 'operatorxr-mjmmet'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r3-47', 'short_insight', 'Counter-Drone Training Outruns Live Ranges', 'Live exercises cannot conveniently reproduce every drone threat or electronic-warfare condition, and counter-UAS skills decay without reps. The useful question is which decisions teams can rehearse in simulation and what still has to be tested in the field.', 'Interceptor launched in April 2026 with FPV, ISR and swarm scenarios and EW effects, and a non-binding MOU with Thales Australia followed in June. Your ADM feature argues for simulated runs before live evaluation; the piece underneath it is how you decide what the simulation has to get right.', '{counter-uas,short-insight,defence-partnership}'::text[], '[{"title": "Operator XR Elevates Counter-Drone Training", "publisher": "The Defense Post", "url": "https://thedefensepost.com/2026/04/15/virtual-counter-drone-training/"}, {"title": "MOU with Thales Australia", "publisher": "Operator XR", "url": "https://operatorxr.com/insights/xtof27qur1rpgqbi27bdwo0pwqxwvx"}, {"title": "ADM feature on simulation and force readiness", "publisher": "Operator XR", "url": "https://operatorxr.com/insights/featured-in-australian-defence-magazine-why-simulation-is-the-missing-piece-in-force-readiness"}]'::jsonb, 1 from companies where slug = 'operatorxr-mjmmet'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r3-48', 'short_insight', 'Grant-Funded VR Needs a Plan Past the Purchase', 'DOJ''s FY2026 Safer Outcomes program funded agency awards in capped, time-limited tracks. A grant buys the kit; keeping scenarios current, training instructors and maintaining equipment needs a budget line that outlives it, and most vendors avoid saying so.', 'Your parent company reports a growing base of agency clients and a recurring-revenue model built on scenarios, analytics and support. A plain piece on how an agency should budget beyond the grant year is one no competitor has written, and it positions the subscription as the point rather than the catch.', '{public-safety-funding,short-insight,buyer-guide}'::text[], '[{"title": "Safer Outcomes program", "publisher": "US DOJ COPS Office", "url": "https://cops.usdoj.gov/saferoutcomes"}, {"title": "xReality Group Reports $20 Million Revenue in FY2026", "publisher": "Kalkine Media", "url": "https://kalkinemedia.com/au/news/announcements/xreality-group-reports-20-million-revenue-in-fy2026-reduces-net-loss-to-122000"}, {"title": "Maximizing Grant Opportunities", "publisher": "Operator XR", "url": "https://operatorxr.com/insights"}]'::jsonb, 2 from companies where slug = 'operatorxr-mjmmet'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
