-- Import for Osso VR (ossovr-6rsei5). Generated from clients/ossovr-6rsei5.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('ossovr-6rsei5', 'Osso VR', 'Justin', 'Justin', 'your nursing platform and research record, and the questions educators ask before a VR score counts', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'osso-01', 'long_form', 'What Makes a Nursing VR Score Valid', 'Osso describes a Test mode in Osso Nurse Training that removes workflow guidance and evaluates independent performance in real time. No page we opened shows those scores mapped to competency sign-off, and the peer-reviewed results Osso lists are surgical studies from 2020 to 2022, not nursing scenarios.', 'Your Bergen New Bridge release reports a June 4, 2026 launch for IV insertion and central line dressing change, with no competency outcomes. Your April 7, 2026 HealthStream post cites a nurse checklist anecdote with no sample or method. No article on your site explains how a Test mode score is defined for a nursing step and what it maps to in competency sign-off.', '{assessment-validity,long-form,company-reported}'::text[], '[{"title": "Health systems", "publisher": "Osso VR", "url": "https://www.ossovr.com/health-systems"}, {"title": "VR surgical training research", "publisher": "Osso VR", "url": "https://www.ossovr.com/vr-surgical-training-research"}, {"title": "HealthStream x Osso VR takeaways, April 7, 2026", "publisher": "Osso VR", "url": "https://www.ossovr.com/post/vr-nurse-training-5-key-takeaways-from-healthstream-x-osso-vr"}]'::jsonb, 0 from companies where slug = 'ossovr-6rsei5'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'osso-02', 'short_insight', 'Keeping Nursing Scenarios Current With Evidence', 'Osso announced its nursing procedural skills platform on October 2, 2025, and a separate release dated November 10, 2025 describes EBSCO Dynamic Health evidence-based skills content in nursing scenarios. Neither page explains how a revised procedure triggers review and redeployment of the matching scenario.', 'Your release gives no numbers beyond the 100,000 professionals claim, which also appears in a 2021 release. No article on your site explains who decides a scenario must change when evidence changes and how educators know which version a nurse completed.', '{content-governance,short-insight,company-reported}'::text[], '[{"title": "Osso VR introduces nursing procedural skills platform, October 2, 2025", "publisher": "Osso VR", "url": "https://www.ossovr.com/press-releases/osso-vr-introduces-new-nursing-procedural-skills-training-platform-opens-early-access-for-healthcare-systems"}, {"title": "HealthStream x Osso VR takeaways, April 7, 2026", "publisher": "Osso VR", "url": "https://www.ossovr.com/post/vr-nurse-training-5-key-takeaways-from-healthstream-x-osso-vr"}]'::jsonb, 1 from companies where slug = 'ossovr-6rsei5'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'osso-03', 'short_insight', 'How a Member Hospital Adopts Nursing VR', 'Bergen New Bridge Medical Center, a 1,070-bed hospital in Paramus, launched Osso Nurse Training on June 4, 2026 and is described as among the first America''s Essential Hospitals members to use it. The association has over 400 members, and no contract terms are public.', 'Your health systems page mentions select LMS integrations, centralized access and support. Your October 2, 2025 release announced early access for members, and your Founders Circle offers early 2026 pricing and curriculum input. No article on your site explains the onboarding sequence at Bergen, from fleet setup to LMS integration to the first nurse practicing.', '{hospital-adoption,short-insight,announcement}'::text[], '[{"title": "Nursing platform early access, October 2, 2025", "publisher": "Osso VR", "url": "https://www.ossovr.com/press-releases/osso-vr-introduces-new-nursing-procedural-skills-training-platform-opens-early-access-for-healthcare-systems"}, {"title": "Health systems", "publisher": "Osso VR", "url": "https://www.ossovr.com/health-systems"}]'::jsonb, 2 from companies where slug = 'ossovr-6rsei5'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
