-- Import for Phoria (phoria-bpoyfs). Generated from clients/phoria-bpoyfs.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('phoria-bpoyfs', 'Phoria', 'Trent', 'Trent', 'your digital twin and REWILD work, and the questions clients ask before they back a new headset', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r3-31', 'short_insight', 'How Julaymba Decided What Could Be Filmed, Built and Shared', 'Screen Australia''s September 2026 report says games outgrow every other screen sector and names no XR funding line. Original XR in Australia has to argue for itself, and the production decisions behind Julaymba are that argument.', 'Julaymba combines 180 and 360 video with constructed 3D environments, with Jabalbina Aboriginal Corporation as production partner safeguarding cultural integrity; it sold at $4.99 on Quest and your project page reports 15,000 views. The piece is how those decisions were made and who made them, written with your partners'' account and approval.', '{indigenous-xr,short-insight,original-ip}'::text[], '[{"title": "Julaymba project page", "publisher": "Phoria", "url": "https://www.phoria.com.au/projects/julaymba"}, {"title": "Julaymba offers Indigenous perspective of the Daintree", "publisher": "National Indigenous Times", "url": "https://nit.com.au/26-03-2025/17030/julaymba-collaboration-offers-indigenous-perspective-of-the-daintree-rainforest"}, {"title": "Screen Currency 2026 and games funding", "publisher": "Screen Australia", "url": "https://www.screenaustralia.gov.au/screen-australia-funds-games-projects-in-every-state-and-territory-as-screen-currency-2026-points-to-sector-growth/"}]'::jsonb, 0 from companies where slug = 'phoria-bpoyfs'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r3-32', 'long_form', 'Passthrough Glasses Reopen the On-Site Digital Twin', 'Meta''s VR Glasses, announced September 2026 for spring 2027, bring full-colour passthrough at around 100 grams. Lighter hardware does not solve registration; it makes the registration problem worth solving again.', 'You put a building model reported as 99 percent accurate into an on-site AR experience at 60 Martin Place in 2020 with Willow and Investa, and your project list includes twins for Arup, Aurecon and the University of Melbourne. The enduring lesson is how the model stays aligned to the building while someone walks through it, and it predates the new headsets.', '{ar-digital-twin,long-form,case-study}'::text[], '[{"title": "Everything announced at Meta Connect 2026", "publisher": "Engadget", "url": "https://www.engadget.com/2267230/everything-announced-at-meta-connect-2026/"}, {"title": "Digital Twin Sixty Martin Place", "publisher": "Phoria", "url": "https://www.phoria.com.au/projects/digital-twin-sixty-martin-place"}, {"title": "Sydney skyscraper built with AR digital twin tech", "publisher": "Building Connection", "url": "https://buildingconnection.com.au/2020/02/28/sydney-skyscraper-built-with-worlds-first-ar-digital-twin-tech/"}]'::jsonb, 1 from companies where slug = 'phoria-bpoyfs'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r3-33', 'short_insight', 'Deciding Whether a New Platform Deserves an Early Release', 'Apple cut Vision Pro production and marketing in January 2026 after weak demand, and every studio that ported early now has a case study in platform timing. The useful version of that story is about what carried across, not what it earned.', 'REWILD Spatial Nature Series is your free visionOS app adapted from the 2019 AR piece made with Netflix, WWF and Google, and Trent has written about the port on LinkedIn. A studio piece on what was reused, what was rebuilt, and how you decide a platform is worth being early on is one other studios will share.', '{platform-strategy,short-insight,app-proof}'::text[], '[{"title": "REWILD Spatial Nature Series", "publisher": "Apple App Store", "url": "https://apps.apple.com/us/app/rewild-spatial-nature-series/id6478364193"}, {"title": "Apple Retreats on Vision Pro as Consumer Demand Falls Short", "publisher": "PYMNTS", "url": "https://www.pymnts.com/apple/2026/apple-retreats-on-vision-pro-as-consumer-demand-falls-short/"}, {"title": "REWILD on Apple Vision Pro", "publisher": "Trent Clews-de Castella on LinkedIn", "url": "https://www.linkedin.com/pulse/rewild-apple-vision-pro-how-spatial-experiences-can-trent-adigc"}]'::jsonb, 2 from companies where slug = 'phoria-bpoyfs'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
