-- Import for Rendever (rendever-autm5m). Generated from clients/rendever-autm5m.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('rendever-autm5m', 'Rendever', 'Kyle', 'Kyle', 'your caregiver training and research work, and the questions care teams ask before they bring VR to older adults', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'ren-01', 'long_form', 'Simulating Dementia in VR Needs Guardrails', 'Rendever launched a family caregiver mode on September 22, 2026 that simulates tasks like brushing teeth and organizing medication with sensory disruptions and hallucinations. The article explains what a short simulation can teach a caregiver and what it should never be taken to mean about every person with dementia.', 'Your release reports 20,000+ caregivers reached since the August 2025 launch and estimates 26,000 older adults and 78,000 family members affected. These are reach counts and estimates, not measured changes in caregiver behavior or patient outcomes. Your release says Dr. Francesca Falzarano speaks after each module. No article on your site explains what that guidance covers or how the modules were designed with her.', '{dementia-training,long-form,company-reported}'::text[], '[{"title": "Rendever family caregiving mode, September 22, 2026", "publisher": "GlobeNewswire", "url": "https://www.globenewswire.com/news-release/2026/09/22/3366560/0/en/rendever-expands-dementia-empathy-training-with-a-new-mode-for-family-caregivers.html"}, {"title": "Rendever dementia training launch", "publisher": "Auganix", "url": "https://www.auganix.org/vr-news-rendever-vr-dementia-training/"}, {"title": "Press", "publisher": "Rendever", "url": "https://www.rendever.com/press"}]'::jsonb, 0 from companies where slug = 'rendever-autm5m'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'ren-02', 'short_insight', 'What a Shared VR Trial Can Prove', 'Rendever''s study page describes an NIA-funded Phase I study comparing shared VR with video calls, using self-reported relationship and well-being measures. The page says the study is still being analyzed for scientific publication and gives no sample size or protocol, so the article treats the findings as initial and unverified.', 'Your research page names the National Institute on Aging as sponsor and UCSB as partner. We could not verify its "largest clinical trial" title. No article on your site explains the sample, how self-reported scales were collected from people with MCI or mild to moderate dementia, or why distant family members were paired.', '{study-design,short-insight,company-reported}'::text[], '[{"title": "Largest clinical trial on VR for dementia", "publisher": "Rendever", "url": "https://www.rendever.com/research/largest-clinical-trial-on-vr-for-dementia"}, {"title": "Press", "publisher": "Rendever", "url": "https://www.rendever.com/press"}, {"title": "Team", "publisher": "Rendever", "url": "https://www.rendever.com/team"}]'::jsonb, 1 from companies where slug = 'rendever-autm5m'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'ren-03', 'short_insight', 'What NIH Funds in Shared VR Care', 'Rendever announced nearly $4.5 million in NIH funding in November 2025, including $3.8 million for the Thrive At Home Program, with UCSB, RAND and Right at Home as partners, per a republished release. A grant is not revenue and an award is not a demonstrated outcome. The article explains what each funded project tests.', 'The Age In Place Tech release describes Thrive At Home. The Forbes wording on your press page names a MultiBrush VR studio that the release does not mention. No article on your site explains what Thrive At Home tests, what MultiBrush is and what evidence would count as success.', '{nih-funding,short-insight,non-revenue}'::text[], '[{"title": "Rendever receives nearly $4.5 million NIH funding", "publisher": "Age In Place Tech", "url": "https://www.ageinplacetech.com/pressrelease/rendever-receives-nearly-45-million-nih-funding-overcome-social-isolation-older-adults"}, {"title": "Press", "publisher": "Rendever", "url": "https://www.rendever.com/press"}, {"title": "Team", "publisher": "Rendever", "url": "https://www.rendever.com/team"}]'::jsonb, 2 from companies where slug = 'rendever-autm5m'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
