-- Import for Sanctuary AI (sanctuary-lnixng). Generated from clients/sanctuary-lnixng.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('sanctuary-lnixng', 'Sanctuary AI', 'Olivia', 'Olivia', 'your hydraulic hand and industrial results, and the questions line engineers ask before they deploy', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-22', 'short_insight', 'Cycle Time Is the Production Gate', 'A wire-insertion task is not production-ready because a robot succeeds once. A line engineer reads success rate and takt together or not at all, and most humanoid announcements publish only the first.', 'Your June 2026 proof of concept hit 99.5 percent or better success at a 2.54 second cycle, judged against a Tier 1 supplier''s live production benchmarks, on commercial robotic platforms rather than Phoenix. The release states both numbers; the article explains why the second is the harder one and what "matched live-line throughput" required.', '{industrial-robotics,short-insight,customer-result}'::text[], '[{"title": "Sanctuary AI Expands Physical AI Strategy to Industrial Robotics", "publisher": "Sanctuary AI", "url": "https://sanctuary.ai/news/sanctuary-ai-expands-physical-ai-strategy-to-industrial-robotics-demonstrating-production-ready-ai-performance/"}, {"title": "Video Friday (June 19 2026)", "publisher": "IEEE Spectrum", "url": "https://spectrum.ieee.org/video-friday-agentic-ai-robot"}, {"title": "Robot plugs wires with 99.5% accuracy", "publisher": "Interesting Engineering", "url": "https://interestingengineering.com/ai-robotics/robot-plugs-wires-with-99-5-accuracy"}]'::jsonb, 0 from companies where slug = 'sanctuary-lnixng'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-23', 'short_insight', 'Zero-Shot Sim-to-Real on a Hydraulic Hand', 'Teleoperation data is expensive to collect at scale, and a policy trained entirely in simulation shifts part of that cost to compute. Hydraulic actuators are harder to simulate than electric ones, which makes a successful transfer worth more than the demo suggests.', 'Your April 2026 demo transferred a sim-only policy to a real hydraulic hand, reorienting a lettered cube ten consecutive times without a drop, after training thousands of hands in parallel in Isaac Lab. What the simulation had to capture well enough for that first transfer to work is the engineering story.', '{sim-to-real,short-insight,demo-proof}'::text[], '[{"title": "Zero-Shot In-Hand Manipulation on Hydraulic Hand", "publisher": "Sanctuary AI", "url": "https://sanctuary.ai/news/sanctuary-ai-demonstrates-zero-shot-in-hand-manipulation-on-hydraulic-hand/"}, {"title": "Sanctuary AI Leverages NVIDIA Isaac Lab", "publisher": "Sanctuary AI", "url": "https://sanctuary.ai/news/sanctuary-ai-leverages-isaac-lab/"}, {"title": "Controlling Advanced Hydraulic Hands Using RL", "publisher": "Sanctuary AI", "url": "https://sanctuary.ai/news/sanctuary-ai-controlling-advanced-hydraulic-hands/"}]'::jsonb, 1 from companies where slug = 'sanctuary-lnixng'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-24', 'long_form', 'What DoF Counts Do Not Tell You About Hands', 'Degrees of freedom tell a buyer how many motions a hand can command. They say nothing about what it can hold, how it responds to a disturbance, or how it performs after repeated factory cycles.', 'Your RL hand work (April 2025) reports in-hand reorientation under a 500 g load not encountered in training, a separate demonstration from the 2026 cube result, and the May 2026 Zeon partnership targets elastomers balancing toughness with tactile precision. The piece sets out the tests a buyer should ask for alongside a spec sheet, without claiming yours win each one.', '{robot-hands,long-form,partnership-proof}'::text[], '[{"title": "Controlling Advanced Hydraulic Hands Using RL", "publisher": "Sanctuary AI", "url": "https://sanctuary.ai/news/sanctuary-ai-controlling-advanced-hydraulic-hands/"}, {"title": "Zeon Invests in Sanctuary AI", "publisher": "Sanctuary AI", "url": "https://sanctuary.ai/news/zeon-invests-in-sanctuary-ai-and-partners-to-advance-specialized-materials-for-dexterous-robotics/"}, {"title": "Zero-Shot In-Hand Manipulation on Hydraulic Hand", "publisher": "Sanctuary AI", "url": "https://sanctuary.ai/news/sanctuary-ai-demonstrates-zero-shot-in-hand-manipulation-on-hydraulic-hand/"}]'::jsonb, 2 from companies where slug = 'sanctuary-lnixng'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
