-- Import for Sanctuary AI (sanctuary-lnixng). Generated from clients/sanctuary-lnixng.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('sanctuary-lnixng', 'Sanctuary AI', 'Olivia', 'Olivia', 'your hydraulic hand and industrial results, and the questions line engineers ask before they deploy', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-22', 'short_insight', 'Cycle Time Is the Production Gate', 'Figure''s BMW Spartanburg pilot ended November 2025 reporting 90,000 parts and a per-shift accuracy goal, with no cycle time published. A line engineer reads success rate and takt together or not at all.', 'Your June 2026 result is 99.5 percent or better success at a 2.54 second cycle, validated against a Tier 1 supplier''s live production benchmarks, on off-the-shelf arms rather than Phoenix. Your release states the two numbers; the article explains why the second one is the harder of the two.', '{industrial-robotics,short-insight,customer-result}'::text[], '[{"title": "Sanctuary AI Expands Physical AI Strategy to Industrial Robotics", "publisher": "Sanctuary AI", "url": "https://sanctuary.ai/news/sanctuary-ai-expands-physical-ai-strategy-to-industrial-robotics-demonstrating-production-ready-ai-performance/"}, {"title": "Humanoid Robots Complete Trial Project at BMW Assembly Plant", "publisher": "Assembly Magazine", "url": "https://www.assemblymag.com/articles/99678-humanoid-robots-complete-trial-project-at-bmw-assembly-plant"}, {"title": "Video Friday (June 19 2026)", "publisher": "IEEE Spectrum", "url": "https://spectrum.ieee.org/video-friday-agentic-ai-robot"}]'::jsonb, 0 from companies where slug = 'sanctuary-lnixng'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-23', 'short_insight', 'Zero-Shot Sim-to-Real on a Hydraulic Hand', 'Teleop data costs $15 to $80 an hour in the West against roughly $3 in China, a labor arbitrage a Vancouver company cannot win. A policy trained entirely in simulation changes the cost of a training hour to compute.', 'Your April 2026 demo transferred a sim-only policy to a real hydraulic hand, reorienting a cube ten consecutive times without a drop, trained on thousands of parallel hands in Isaac Lab. Hydraulics are harder to simulate than electric actuators, which is why the result deserves a longer explanation than a release.', '{sim-to-real,short-insight,demo-proof}'::text[], '[{"title": "Zero-Shot In-Hand Manipulation on Hydraulic Hand", "publisher": "Sanctuary AI", "url": "https://sanctuary.ai/news/sanctuary-ai-demonstrates-zero-shot-in-hand-manipulation-on-hydraulic-hand/"}, {"title": "Sanctuary AI Leverages NVIDIA Isaac Lab", "publisher": "Sanctuary AI", "url": "https://sanctuary.ai/news/sanctuary-ai-leverages-isaac-lab/"}, {"title": "Humanoid Robot Data Collection Costs 2026", "publisher": "DataXPower", "url": "https://www.dataxpower.com/blog/humanoid-robot-data-collection-cost"}]'::jsonb, 1 from companies where slug = 'sanctuary-lnixng'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-24', 'long_form', 'What DoF Counts Do Not Tell You About Hands', 'Unitree''s H2 Plus (June 2026) lists 22-DoF tactile hands at a $100,000 robot price, matching your 21-DoF hydraulic hand on paper. Matching counts say nothing about force density, disturbance rejection or surface wear at factory cycle counts.', 'Your RL hand work reports in-hand reorientation under a 500 g load not seen in training, and the May 2026 Zeon partnership targets elastomers that balance toughness with tactile precision. The piece sets out the measurements a buyer should ask for instead of DoF, without claiming yours win on each.', '{robot-hands,long-form,partnership-proof}'::text[], '[{"title": "Controlling Advanced Hydraulic Hands Using RL", "publisher": "Sanctuary AI", "url": "https://sanctuary.ai/news/sanctuary-ai-controlling-advanced-hydraulic-hands/"}, {"title": "Zeon Invests in Sanctuary AI", "publisher": "Sanctuary AI", "url": "https://sanctuary.ai/news/zeon-invests-in-sanctuary-ai-and-partners-to-advance-specialized-materials-for-dexterous-robotics/"}, {"title": "Unitree H2 Humanoid Robot specs", "publisher": "Robozaps", "url": "https://blog.robozaps.com/b/unitree-h2-review"}]'::jsonb, 2 from companies where slug = 'sanctuary-lnixng'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
