-- Import for Schemata (schemata-lnebhz). Generated from clients/schemata-lnebhz.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('schemata-lnebhz', 'Schemata', 'James', 'James', 'your work at Whiteman and Altus, and the questions maintenance leads ask before they trust AI at the aircraft', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-13', 'short_insight', 'Cited Answers From Technical Orders', 'The Pentagon''s January 2026 AI strategy put GenAI.mil in front of millions of personnel. A maintainer does not need a chat window; they need the right paragraph of the right TO, with the citation, at the aircraft.', 'Your July 2026 release answers questions only from ingested Technical Orders, manuals, SOPs and videos, with citations, at Whiteman AFB. How retrieval behaves when the TO is silent or two documents conflict is the piece, and it needs your engineers in the room.', '{grounded-retrieval,short-insight,product-release}'::text[], '[{"title": "Schemata Answers Questions at the Point of Need", "publisher": "Schemata", "url": "https://www.schemata.com/news/the-schemata-drop-schemata-answers-questions-at-the-point-of-need"}, {"title": "AI Strategy (January 12 2026)", "publisher": "Department of War", "url": "https://media.defense.gov/2026/Jan/12/2003855671/-1/-1/0/ARTIFICIAL-INTELLIGENCE-STRATEGY-FOR-THE-DEPARTMENT-OF-WAR.PDF"}, {"title": "Pentagon rolls out major reforms of R&D, AI", "publisher": "Breaking Defense", "url": "https://breakingdefense.com/2026/01/pentagon-rolls-out-major-reforms-of-rd-ai/"}]'::jsonb, 0 from companies where slug = 'schemata-lnebhz'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-14', 'long_form', 'One Scan, Twice the Training Slots', 'Boeing''s 2026 outlook calls for 728,000 technicians over 20 years, and units train on single physical assets that are also needed on the line. The ROI of a scan shows up in asset availability before it shows up in learning outcomes.', 'Altus AFB reported a 20 percent increase in bus availability and doubled inspection opportunities after one bus was scanned into tablet-based training. The equipment-availability math is the argument your site states once as a quote and never works through.', '{training-digital-twin,long-form,customer-quote}'::text[], '[{"title": "AI-Native Training for the Next Generation of Airmen", "publisher": "Schemata", "url": "https://www.schemata.com/news/ai-native-training-for-the-next-generation-of-airmen"}, {"title": "The 2026 Boeing Technician Outlook", "publisher": "ATEC", "url": "https://www.atec-amt.org/news/the-2026-boeing-technician-outlook-a-closer-look"}, {"title": "The Manual, Rewritten", "publisher": "Schemata", "url": "https://www.schemata.com/news/the-schematic-the-manual-rewritten"}]'::jsonb, 1 from companies where slug = 'schemata-lnebhz'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-15', 'short_insight', 'Animating a Scan Is Harder Than Scanning It', 'Nvidia''s Cosmos 3 (June 2026) generates plausible worlds; maintenance training needs the exact asset, with parts that move the way the real ones do. A photoreal capture has no part hierarchy, so motion is a second job.', 'Your August 2026 release adds system motion, animation and exploded views to scanned assets, viewable on a personal device. What it takes to segment a capture into articulated parts and keep it rendering on a tablet is the engineering story, pending an interview.', '{reality-capture,short-insight,product-release}'::text[], '[{"title": "Simulating How Your Systems Work Together", "publisher": "Schemata", "url": "https://www.schemata.com/news/the-schemata-drop-simulating-how-your-systems-work-together"}, {"title": "Nvidia''s Cosmos 3 open AI world model", "publisher": "Axios", "url": "https://www.axios.com/2026/06/01/nvidia-ai-push-cosmos-3-world-model"}, {"title": "The Next Frontier is Physical", "publisher": "Schemata", "url": "https://www.schemata.com/news/the-schematic-the-next-frontier-is-physical"}]'::jsonb, 2 from companies where slug = 'schemata-lnebhz'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
