-- Import for Schemata (schemata-lnebhz). Generated from clients/schemata-lnebhz.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('schemata-lnebhz', 'Schemata', 'James', 'James', 'your work at Whiteman and Altus, and the questions maintenance leads ask before they trust AI at the aircraft', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-13', 'short_insight', 'Cited Answers From Technical Orders', 'The Pentagon''s January 2026 AI strategy made general-purpose AI a stated priority across the department. A maintainer does not need a chat window; they need the right paragraph of the right TO, with its citation, at the aircraft.', 'Your July 2026 release retrieves and cites ingested Technical Orders, manuals, SOPs and videos, with a Whiteman AFB maintainer example, and already explains why citations matter. The next piece is what happens when approved documents disagree, an equipment variant changes the procedure, or the answer is not there.', '{grounded-retrieval,short-insight,product-release}'::text[], '[{"title": "Schemata Answers Questions at the Point of Need", "publisher": "Schemata", "url": "https://www.schemata.com/news/the-schemata-drop-schemata-answers-questions-at-the-point-of-need"}, {"title": "AI Strategy (January 12 2026)", "publisher": "Department of War", "url": "https://media.defense.gov/2026/Jan/12/2003855671/-1/-1/0/ARTIFICIAL-INTELLIGENCE-STRATEGY-FOR-THE-DEPARTMENT-OF-WAR.PDF"}, {"title": "Pentagon rolls out major reforms of R&D, AI", "publisher": "Breaking Defense", "url": "https://breakingdefense.com/2026/01/pentagon-rolls-out-major-reforms-of-rd-ai/"}]'::jsonb, 0 from companies where slug = 'schemata-lnebhz'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-14', 'long_form', 'One Scan, Twice the Inspection Opportunities', 'Boeing''s 2026 outlook calls for 728,000 technicians over 20 years, and units train on single physical assets that are also needed on the line. The payoff of a scan shows up in asset availability before it shows up in learning outcomes.', 'An Altus AFB instructor reported 20 percent more bus availability and double the inspection opportunities after one bus was scanned into tablet-based training. That is an attributed customer report; the article asks for the baseline and schedule and works through what changed when the physical bus no longer served every lesson.', '{training-digital-twin,long-form,customer-quote}'::text[], '[{"title": "AI-Native Training for the Next Generation of Airmen", "publisher": "Schemata", "url": "https://www.schemata.com/news/ai-native-training-for-the-next-generation-of-airmen"}, {"title": "The 2026 Boeing Technician Outlook", "publisher": "ATEC", "url": "https://www.atec-amt.org/news/the-2026-boeing-technician-outlook-a-closer-look"}, {"title": "The Manual, Rewritten", "publisher": "Schemata", "url": "https://www.schemata.com/news/the-schematic-the-manual-rewritten"}]'::jsonb, 1 from companies where slug = 'schemata-lnebhz'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-15', 'short_insight', 'Animating a Scan Is Harder Than Scanning It', 'A faithful-looking scan is enough for recognition. Maintenance training also needs trainees to see how a component moves and fits with the rest of the system, and a photoreal capture has no part hierarchy on its own.', 'Your August 2026 release adds system motion, animation and exploded views to scanned assets, viewable on a personal device. How a capture becomes a set of parts a trainee can manipulate (segmentation, rigging, validated movement) is an interview-led piece, and nothing on your site describes it.', '{reality-capture,short-insight,product-release}'::text[], '[{"title": "Simulating How Your Systems Work Together", "publisher": "Schemata", "url": "https://www.schemata.com/news/the-schemata-drop-simulating-how-your-systems-work-together"}, {"title": "The Next Frontier is Physical", "publisher": "Schemata", "url": "https://www.schemata.com/news/the-schematic-the-next-frontier-is-physical"}, {"title": "A First Look at Schemata''s Platform", "publisher": "Schemata", "url": "https://www.schemata.com/news/a-first-look-at-schematas-platform"}]'::jsonb, 2 from companies where slug = 'schemata-lnebhz'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
