-- Import for Sentient Computing (sentient-5hgcik). Generated from clients/sentient-5hgcik.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('sentient-5hgcik', 'Sentient Computing', 'Chris', 'Chris', 'your StockyardViz and InDI twins, your mine safety work, and the questions operators ask before they fund a twin', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-10', 'short_insight', 'What Makes a Stockyard Twin Trustworthy', 'Around 90 percent of surveyed miners are using or piloting digital twins, and Datamine shipped one inside MineScape 2026 in March. Most twins are renders; a trustworthy one has a stated accuracy and a data path an operator can audit.', 'StockyardViz publishes roughly 25 cm geometric accuracy and an approximately 15 percent Q1 material-allocation efficiency gain at an iron ore producer, with an 8 to 12 week implementation. How stacker positions, assays and weightometer data reach the model is a question for your engineers, and the answer is the article.', '{mining-digital-twin,short-insight,product-proof}'::text[], '[{"title": "StockyardViz", "publisher": "Sentient Computing", "url": "https://sencom.com.au/stockyardviz/"}, {"title": "Sentient at GRX26 Innovation Zone", "publisher": "Sentient Computing", "url": "https://sencom.com.au/2026/grx26/"}, {"title": "The optimisation of digital twins for mine safety", "publisher": "Mine Australia", "url": "https://mine.nridigital.com/mine_australia_dec25/the_optimisation_of_digital_twins_for_mine_safety"}]'::jsonb, 0 from companies where slug = 'sentient-5hgcik'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-11', 'long_form', 'Site Tourism Is the Twin ROI Nobody Models', 'Vendors sell twins on commissioning-time savings; the figure a CFO signs off on is flights. A twin that replaces a site visit has to integrate with permits, SCADA and ERP first, or the visit still happens.', 'Your InDI page cites a resource company saving upwards of $3M a year on remote trips costing around 10k AUD each, with payback in months, and lists ERP, SCADA, permit, IoT and DMS integrations. No article shows the integration surface that made the number real.', '{digital-twin-roi,long-form,product-proof}'::text[], '[{"title": "Digital Twin (InDI)", "publisher": "Sentient Computing", "url": "https://sencom.com.au/products/digital-twin/"}, {"title": "5 Industry Trends for 2026", "publisher": "Unity", "url": "https://unity.com/blog/top-trends-redefining-industry-in-2026"}, {"title": "Sentient Joins Unity Partner Program", "publisher": "Sentient Computing", "url": "https://sencom.com.au/2026/sentient-joins-unity-partner-program-as-a-certified-authorized-service-partner/"}]'::jsonb, 1 from companies where slug = 'sentient-5hgcik'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-12', 'linkedin_post', 'LTIs Rise While Fatalities Fall', 'WA mineral industry fatalities dropped to one in 2023-24 while lost-time injuries rose to 591 and LTIFR climbed to 2.126 per million hours. The gap between the two curves is the case for training that targets habits, not rule knowledge.', 'Your Barminco modules (2021) report zero pedestrian-to-vehicle incidents among 200+ trainees, and your 2026 Macmahon work uses a classroom, VR driving module and field verification sequence on priority rules. Pair the dated Barminco figure with the fresh WorkSafe data.', '{mine-safety-training,linkedin-post,case-study}'::text[], '[{"title": "Safety performance in the Western Australian mineral industry 2023-24", "publisher": "WorkSafe WA", "url": "https://www.worksafe.wa.gov.au/system/files/documents/2025-11/MS_RP_Safety-performance-2023-24.pdf"}, {"title": "Barminco VR Underground Safety Modules", "publisher": "Sentient Computing", "url": "https://sencom.com.au/case-studies/barminco-vr-underground-safety-modules/"}, {"title": "Closing the Gap Between Training and Performance", "publisher": "Sentient Computing", "url": "https://sencom.com.au/case-studies/closing-the-gap-between-training-and-performance/"}]'::jsonb, 2 from companies where slug = 'sentient-5hgcik'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
