-- Import for Sentient Computing (sentient-5hgcik). Generated from clients/sentient-5hgcik.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('sentient-5hgcik', 'Sentient Computing', 'Chris', 'Doug', 'your StockyardViz and InDI twins, your mine safety work, and the questions operators ask before they fund a twin', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-10', 'short_insight', 'What Makes a Stockyard Twin Trustworthy', 'Around 90 percent of surveyed miners are using or piloting digital twins, and Datamine shipped one inside MineScape 2026 in March. Most twins are renders; a trustworthy one has a stated accuracy and a data path an operator can question.', 'StockyardViz models stackers and reclaimers at 25 cm scale and your GRX26 page reports approximately 15 percent improvement in material-allocation efficiency in Q1 at an iron ore producer. Your FAQ already names the inputs (equipment positions, belt weightometers, lab assays, geometry); how they are calibrated, refreshed and reconciled when they arrive at different times is the engineering story.', '{mining-digital-twin,short-insight,product-proof}'::text[], '[{"title": "StockyardViz", "publisher": "Sentient Computing", "url": "https://sencom.com.au/stockyardviz/"}, {"title": "Sentient at GRX26 Innovation Zone", "publisher": "Sentient Computing", "url": "https://sencom.com.au/2026/grx26/"}, {"title": "The optimisation of digital twins for mine safety", "publisher": "Mine Australia", "url": "https://mine.nridigital.com/mine_australia_dec25/the_optimisation_of_digital_twins_for_mine_safety"}]'::jsonb, 0 from companies where slug = 'sentient-5hgcik'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-11', 'long_form', 'Site Tourism Is the Twin ROI Nobody Models', 'Vendors sell twins on commissioning-time savings; the number a resource company can actually count is trips to a remote asset. A twin replaces a visit only once the information specialists needed on site is available remotely.', 'Your InDI case reports an unnamed major resource company estimating savings upwards of AUD 3M a year, with remote round trips costing upwards of AUD 10,000 and first-months savings covering deployment, on a build that mapped data to DMS and ERP. Which visits became avoidable, and what had to be visible first, is the article.', '{digital-twin-roi,long-form,product-proof}'::text[], '[{"title": "Digital Twin (InDI)", "publisher": "Sentient Computing", "url": "https://sencom.com.au/products/digital-twin/"}, {"title": "5 Industry Trends for 2026", "publisher": "Unity", "url": "https://unity.com/blog/top-trends-redefining-industry-in-2026"}, {"title": "Sentient Joins Unity Partner Program", "publisher": "Sentient Computing", "url": "https://sencom.com.au/2026/sentient-joins-unity-partner-program-as-a-certified-authorized-service-partner/"}]'::jsonb, 1 from companies where slug = 'sentient-5hgcik'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-12', 'short_insight', 'From Knowing Priority Rules to Using Them on Site', 'WA mineral industry fatalities fell to one in 2023-24 while lost-time injuries rose to 591. The numbers do not prove any training method; they do show that rule knowledge and rule use are different problems.', 'Your Macmahon case did not replace classroom or field training; it added a VR mine-road module between them for repeated site-specific decisions, then checked those decisions under supervision. Your Barminco modules (2021) report zero pedestrian-to-vehicle incidents among 200-plus trainees; use it dated and attributed.', '{mine-safety-training,short-insight,case-study}'::text[], '[{"title": "Closing the Gap Between Training and Performance", "publisher": "Sentient Computing", "url": "https://sencom.com.au/case-studies/closing-the-gap-between-training-and-performance/"}, {"title": "Safety performance in the Western Australian mineral industry 2023-24", "publisher": "WorkSafe WA", "url": "https://www.worksafe.wa.gov.au/system/files/documents/2025-11/MS_RP_Safety-performance-2023-24.pdf"}, {"title": "Barminco VR Underground Safety Modules", "publisher": "Sentient Computing", "url": "https://sencom.com.au/case-studies/barminco-vr-underground-safety-modules/"}]'::jsonb, 2 from companies where slug = 'sentient-5hgcik'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
