-- Import for Simbe Robotics (simbe-f2jstz). Generated from clients/simbe-f2jstz.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('simbe-f2jstz', 'Simbe Robotics', 'Brad', 'Brad', 'your Tally fleet and UL 3300 certification, and the questions retailers ask before a robot shares the aisle', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'simbe-01', 'short_insight', 'From Pilot to Chainwide in Under Three Months', 'HomeBase USA, a nine-location retailer, expanded Simbe to all locations in less than three months after a pilot, per a July 30, 2026 release. The release reports 92% fewer pricing errors and 58% fewer controllable out-of-stocks from the pilot, with no baseline or measurement period.', 'Your release names Tally, fixed sensors and RFID and does not state how many stores the pilot covered. Your September 21, 2026 release counts 3,000+ units under contract, which is not a deployed count. No article on your site explains which data quality signals decided the pilot-to-chainwide conversion.', '{pilot-conversion,short-insight,company-reported}'::text[], '[{"title": "HomeBase USA deploys Simbe chainwide", "publisher": "Simbe", "url": "https://www.simberobotics.com/about/newsroom/homebase-usa-deploys-simbe-chainwide-following-rapid-pilot-success"}, {"title": "Simbe surpasses 3,000 units", "publisher": "PR Newswire", "url": "https://www.prnewswire.com/news-releases/simbe-surpasses-3-000-units-marking-the-largest-autonomous-shelf-intelligence-fleet-in-retail-302884117.html"}, {"title": "Tally 4.0", "publisher": "Simbe", "url": "https://www.simberobotics.com/about/newsroom/simbe-unveils-tally-4-0-the-next-generation-of-autonomous-retail-robot-powering-store-intelligence-via-physical-ai"}]'::jsonb, 0 from companies where slug = 'simbe-f2jstz'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'simbe-02', 'short_insight', 'Shelf Accuracy Claims Need Their Denominators', 'Simbe''s May 2025 release reports 98.7% SKU-level identification accuracy and over 99.3% shelf-condition recall, with no test population or evaluation protocol on the page. The two figures measure different things, and the article asks what was counted for each.', 'Your Simbe Vision release cites 60 billion shelf images analyzed, 18 million SKUs and 5,400 items scanned per hour, all vendor-reported. No article on your site explains how recall is measured on a shelf, what counts as a miss and which shelf conditions were hardest to detect.', '{accuracy-metrics,short-insight,company-reported}'::text[], '[{"title": "Simbe expands next-generation computer vision", "publisher": "Simbe", "url": "https://www.simberobotics.com/about/newsroom/simbe-expands-next-generation-computer-vision-technology-to-transform-retail-execution"}]'::jsonb, 1 from companies where slug = 'simbe-f2jstz'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'simbe-03', 'long_form', 'Certifying a Robot That Shares the Aisle', 'UL Solutions certified Simbe''s Tally and its charging dock under UL 3300 on March 11, 2026, and calls it UL Solutions'' first global certification of a public-facing robot. Testing covered fire and shock hazards and safe autonomous mobility in public environments.', 'UL says OSHA added UL 3300 to a recognized standards list and gives no effective date. Certification does not replace a retailer''s site-specific safety assessment. No article on your site explains what UL 3300 tests and what a retailer''s safety team still has to assess before the robot goes into a busy aisle.', '{robot-safety,long-form,published-result}'::text[], '[{"title": "first global certification for a public-facing robot", "publisher": "UL Solutions", "url": "https://www.ul.com/news/ul-solutions-grants-its-first-global-certification-public-facing-robot-simbes-tally-autonomous"}, {"title": "Simbe surpasses 3,000 units", "publisher": "PR Newswire", "url": "https://www.prnewswire.com/news-releases/simbe-surpasses-3-000-units-marking-the-largest-autonomous-shelf-intelligence-fleet-in-retail-302884117.html"}, {"title": "Tally 4.0", "publisher": "Simbe", "url": "https://www.simberobotics.com/about/newsroom/simbe-unveils-tally-4-0-the-next-generation-of-autonomous-retail-robot-powering-store-intelligence-via-physical-ai"}]'::jsonb, 2 from companies where slug = 'simbe-f2jstz'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
