-- Import for Start Beyond (startbeyond-duipnb). Generated from clients/startbeyond-duipnb.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('startbeyond-duipnb', 'Start Beyond', 'Angus', 'Angus', 'your Woolworths and aged care deployments, and the questions training leads ask before they scale VR', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-16', 'short_insight', 'Managing Enterprise VR Fleets as Meta''s Offer Changes', 'Meta ended commercial Quest sales and new Horizon Managed Services subscriptions on February 20 2026; existing customers keep support to January 4 2030. The clock on provisioning, kiosk lockdown and remote wipe is now visible.', 'Your Woolworths deployment runs 2,000 headsets across 1,000+ stores on Strivr, the largest fleet of its kind in Australian retail. No piece on your site tells a retail IT lead what the next four years of fleet management look like.', '{vr-fleet-management,short-insight,customer-story}'::text[], '[{"title": "Meta Is Shutting Down Its Quest For Business Program", "publisher": "UploadVR", "url": "https://www.uploadvr.com/meta-is-shutting-down-its-quest-for-business-program/"}, {"title": "Woolworths Group Training", "publisher": "Start Beyond", "url": "https://www.startbeyond.co/case-studies/woolworths-vr-training"}, {"title": "Meta to stop selling Quest headsets to businesses", "publisher": "SiliconANGLE", "url": "https://siliconangle.com/2026/01/16/meta-stop-selling-quest-headsets-businesses-discontinue-multiple-vr-features/"}]'::jsonb, 0 from companies where slug = 'startbeyond-duipnb'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-17', 'long_form', '360 Video or Real-Time 3D for Accredited Training', 'World Labs opened a World API in January 2026 that generates navigable 3D scenes from text or panoramas. Accredited units still need actor realism, a tablet fallback and an auditor who accepts the scenario, and generative 3D has none of that yet.', 'Your Limestone Coast build delivers ASQA-compliant aged care and disability units on live-action 360 with branching, one facilitator to 28 learners on headsets and iPads. The tradeoff piece (reshoot cost versus assessment validity) is one only a studio that has shipped both can write.', '{immersive-content-format,long-form,customer-story}'::text[], '[{"title": "Limestone Coast case study", "publisher": "Start Beyond", "url": "https://www.startbeyond.co/case-studies/limestone-coast"}, {"title": "Announcing the World API", "publisher": "World Labs", "url": "https://www.worldlabs.ai/blog/announcing-the-world-api"}, {"title": "Interactive 360 Aged Care Training", "publisher": "Start Beyond", "url": "https://www.startbeyond.co/case-studies/interactive-360-aged-care-training"}]'::jsonb, 1 from companies where slug = 'startbeyond-duipnb'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-18', 'short_insight', 'Confidence Is Not Competence Under the Aged Care Act', 'The new Aged Care Act commenced November 1 2025 and providers now report training against it. Self-reported confidence is the easiest outcome to collect and the weakest one to defend.', 'Sacadi VR launched in February 2026 for aged care compliance, and your strongest published outcome is Reject Shop''s "very confident" rising from 18 to 68 percent (n=95), explicitly a participant confidence measure. The article maps the ladder from confidence to observed competence and what each rung costs.', '{training-measurement,short-insight,case-study}'::text[], '[{"title": "About the new Aged Care Act", "publisher": "Aged Care Quality and Safety Commission", "url": "https://www.agedcarequality.gov.au/providers/reform-changes-providers/about-new-aged-care-act-and-key-changes-providers"}, {"title": "Start Beyond rolls out VR training to help aged care meet new compliance rules", "publisher": "iTWire", "url": "https://itwire.com/science-news/health/start-beyond-rolls-out-vr-training-to-help-aged-care-meet-new-compliance-rules"}, {"title": "Minaca VR case study", "publisher": "Start Beyond", "url": "https://www.startbeyond.co/case-studies/minaca-vr"}]'::jsonb, 2 from companies where slug = 'startbeyond-duipnb'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
