-- Import for Start Beyond (startbeyond-duipnb). Generated from clients/startbeyond-duipnb.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('startbeyond-duipnb', 'Start Beyond', 'Angus', 'Angus', 'your Woolworths and aged care deployments, and the questions training leads ask before they scale VR', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-16', 'short_insight', 'Managing Enterprise VR Fleets as Meta''s Offer Changes', 'Meta ended commercial Quest sales and new Horizon Managed Services subscriptions on February 20 2026; existing customers keep support to January 4 2030. Large deployments now depend on three parties, and the clock on who does what is visible.', 'Your Woolworths program spans more than 1,000 stores and 2,000 headsets, with your case crediting Strivr''s infrastructure for hardware, security, deployment and analytics. A joint piece on which parts of that deployment sit with the headset maker, the management platform and the content studio is one retail IT leads will read.', '{vr-fleet-management,short-insight,customer-story}'::text[], '[{"title": "An update on Meta for Work", "publisher": "Meta for Work", "url": "https://work.meta.com/help/1964851097790493"}, {"title": "Woolworths Group Training", "publisher": "Start Beyond", "url": "https://www.startbeyond.co/case-studies/woolworths-vr-training"}, {"title": "Meta Is Shutting Down Its Quest For Business Program", "publisher": "UploadVR", "url": "https://www.uploadvr.com/meta-is-shutting-down-its-quest-for-business-program/"}]'::jsonb, 0 from companies where slug = 'startbeyond-duipnb'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-17', 'long_form', '360 Video or Real-Time 3D for Accredited Training', 'World Labs opened a World API in January 2026 that generates navigable 3D scenes from text or panoramas. Live-action 360 puts a learner face to face with a believable care interaction; real-time 3D gives a team freedom to change the environment, and each serves a different assessment design.', 'Your Limestone Coast build delivers aged care and disability units on live-action branching 360, one facilitator to 28 learners on headsets and iPads, alongside accredited training. The comparison a studio that has shipped both can write is actor performance, repeatability, update cost and the evidence an assessor needs for a specific course.', '{immersive-content-format,long-form,customer-story}'::text[], '[{"title": "Limestone Coast case study", "publisher": "Start Beyond", "url": "https://www.startbeyond.co/case-studies/limestone-coast"}, {"title": "Announcing the World API", "publisher": "World Labs", "url": "https://www.worldlabs.ai/blog/announcing-the-world-api"}, {"title": "Interactive 360 Aged Care Training", "publisher": "Start Beyond", "url": "https://www.startbeyond.co/case-studies/interactive-360-aged-care-training"}]'::jsonb, 1 from companies where slug = 'startbeyond-duipnb'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-18', 'short_insight', 'Confidence Is Not Competence in Aged Care', 'The new Aged Care Act commenced November 1 2025 and providers are building evidence of how staff make and apply care decisions. Self-reported confidence is the easiest outcome to collect and the weakest to defend.', 'Your Reject Shop pilot of Minaca measured "very confident" rising from 18 to 68 percent across 95 retail staff, and Sacadi VR (February 2026) is described as supporting assessment in structured aged care programs. The article maps what a scenario record can show and what still has to be observed on the job, without splicing the retail result into an aged care claim.', '{training-measurement,short-insight,case-study}'::text[], '[{"title": "About the new Aged Care Act", "publisher": "Aged Care Quality and Safety Commission", "url": "https://www.agedcarequality.gov.au/providers/reform-changes-providers/about-new-aged-care-act-and-key-changes-providers"}, {"title": "Sacadi VR", "publisher": "Start Beyond", "url": "https://www.startbeyond.co/sacadivr"}, {"title": "Minaca VR case study", "publisher": "Start Beyond", "url": "https://www.startbeyond.co/case-studies/minaca-vr"}]'::jsonb, 2 from companies where slug = 'startbeyond-duipnb'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
