-- Import for Taqtile (taqtile-2zt59d). Generated from clients/taqtile-2zt59d.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('taqtile-2zt59d', 'Taqtile', 'Dirck', 'Dirck', 'your Manifest releases and Paks pilot, and the questions frontline leaders ask before they change devices', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'taq-01', 'long_form', 'The Step Record Outlives the Headset', 'The Register reported in October 2024 that Microsoft said HoloLens 2 support, including security updates, ends December 31, 2027. Taqtile''s January 14, 2026 blog describes a step-level record with step IDs, prerequisites, timestamps and pass or fail with variance reasons. The article asks which parts of a procedure record survive a device change.', 'Your January 14, 2026 post lists those fields and gives no numbers. Your Guides Migration page says HoloLens support ends in 2026, a separate event from the December 31, 2027 device date, so the article states each date separately. No article on your site explains how a step record is stored and reused across a phone, a tablet and a headset.', '{work-instruction-data,long-form,company-reported}'::text[], '[{"title": "Manifest Everywhere, December 18, 2025", "publisher": "Taqtile", "url": "https://www.taqtile.com/insights/posts/manifest-mobile-work-instructions/"}, {"title": "AI video and digital work instructions, January 14, 2026", "publisher": "Taqtile", "url": "https://www.taqtile.com/blog/ai-video-digital-work-instructions-frontline-training/"}]'::jsonb, 0 from companies where slug = 'taqtile-2zt59d'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'taq-02', 'short_insight', 'When a Procedure Moves to a Phone', 'Taqtile''s Manifest 4.3 update of December 18, 2025 runs Work, Faults, Connect and Review on Android phones and tablets and on Chrome-capable devices. The page does not mention offline operation, so the article answers it with the engineers.', 'Your separate Manifest Maker 3.0 release adds cloud accounts, cross-device authoring sync and two-way sync with Manifest once a procedure is linked to an Asset Class. Maker''s release notes list its App Store publication on December 19, and the blog post is dated December 22. Neither announcement says what happens to a procedure edit made on a phone while offline. No article on your site explains what is saved locally and what waits for a connection.', '{mobile-authoring,short-insight,shipped-feature}'::text[], '[{"title": "Manifest Everywhere, December 18, 2025", "publisher": "Taqtile", "url": "https://www.taqtile.com/insights/posts/manifest-mobile-work-instructions/"}]'::jsonb, 1 from companies where slug = 'taqtile-2zt59d'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'taq-03', 'short_insight', 'From Training Center Pilot to Plant Floor', 'A Taqtile case study dated August 21, 2025 describes a Manifest pilot at the Paks Nuclear Power Plant training center in Hungary on HoloLens 2 and iPad, with a broader rollout planned. The only figure is customer context: it takes at least two years for a repairer to work independently.', 'Your case study reports no pilot result and quotes Béla Sitkei. The Delta Black Aerospace alliance of October 29, 2025 is a separate strategic alliance with undisclosed terms and says nothing about Paks. No article on your site explains what a nuclear training center needs to see before a pilot becomes a rollout.', '{pilot-to-rollout,short-insight,pilot-stage}'::text[], '[{"title": "Delta Black and Taqtile partner", "publisher": "Taqtile", "url": "https://www.taqtile.com/news/delta-black-and-taqtile-partner-to-modernize-military-drone-operations/"}]'::jsonb, 2 from companies where slug = 'taqtile-2zt59d'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
