-- Import for Transfr (transfr-rfppux). Generated from clients/transfr-rfppux.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('transfr-rfppux', 'Transfr', null, null, 'your San Luis Valley, San Antonio and reentry programs, and the questions educators ask before they scale VR career training', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'tfr-01', 'short_insight', 'Three Headsets, Six Counties, 260 Students', 'Transfr''s March 2, 2026 San Luis Valley story reports three headsets reaching 260+ students across six counties and 8,000 square miles. Reach and hours logged are usage counts. The page says the headsets rotate among Monte Vista High School, Delta Center and a Boys & Girls Club.', 'Your story reports 200+ sessions and 105 hours logged in total, and a 300+ student figure that is a projection. No article on your site explains the schedule, transport, maintenance and staffing behind that rotation.', '{shared-headsets,short-insight,company-reported}'::text[], '[{"title": "San Luis Valley Career-Connected Pathways Partnership", "publisher": "Transfr", "url": "https://transfrinc.com/resources/customer-stories/san-luis-valley-career-connected-pathways-partnership"}, {"title": "Blog", "publisher": "Transfr", "url": "https://transfrinc.com/resources/blog"}]'::jsonb, 0 from companies where slug = 'transfr-rfppux'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'tfr-02', 'short_insight', 'Designing a Four-Day VR Career Lesson', 'San Antonio ISD reported 1,100+ students participating in Transfr sims, with 30 goggle sets bought this year after 8 earlier sets, per an April 29, 2026 republication of the district''s story. The four-day sequence includes a 23-question interest inventory, and the stated goal is at least two sims per student.', 'These are district-reported usage figures, not outcomes, and the page does not confirm that every student completed two sims. Your January 27, 2026 post covers how to start a career exploration program with VR. No article on your site explains how a teacher moves a class from an initial career choice to a useful discussion after the headset comes off.', '{career-exploration,short-insight,district-reported}'::text[], '[{"title": "San Antonio ISD VR goggles", "publisher": "Transfr", "url": "https://transfrinc.com/resources/news/san-antonio-isd-vr-goggles-bring-career-possibilities-to-life"}, {"title": "Blog", "publisher": "Transfr", "url": "https://transfrinc.com/resources/blog"}]'::jsonb, 1 from companies where slug = 'transfr-rfppux'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'tfr-03', 'long_form', 'VR Reentry Training Needs Cohort Data', 'Transfr''s August 19, 2026 post reports 17 graduates across two Leon County Detention Facility cohorts, 11 since released, after a 120-hour blended training program. That is not 120 hours of VR per learner. The 18 union recruits at Scott County Jail within six months are a separate facility-level result.', 'Your post cites RAND recidivism figures second hand, says VR-specific longitudinal data is limited and calls the gap a research agenda, not a marketing problem. No article on your site specifies a follow-up design: which outcomes each partner tracks after release and for how long.', '{reentry-training,long-form,company-reported}'::text[], '[{"title": "Can VR job training reduce recidivism", "publisher": "Transfr", "url": "https://transfrinc.com/resources/blog/vr-training-reduce-recidivism"}, {"title": "Back to school, back to evidence", "publisher": "Transfr", "url": "https://transfrinc.com/resources/blog/vr-in-education-edtech-evidence-standards"}]'::jsonb, 2 from companies where slug = 'transfr-rfppux'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
