-- Import for Veeda AI (veeda-4idwaw). Generated from clients/veeda-4idwaw.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('veeda-4idwaw', 'Veeda AI', 'Sanja', 'Sanja', 'your founding thesis on simulated worlds, and the questions robotics teams ask before they trust one', true, to_jsonb('1 long-form article + 1 short insight + 1 LinkedIn post'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r3-40', 'linkedin_post', 'Why Imitation Learning Alone Will Not Scale', 'Most of the robotics field is still collecting teleoperated demonstrations, and your founding thesis is that embodied intelligence will not emerge from imitation learning alone. Robots must also act, fail and try again, and that needs a world to do it in.', 'Your homepage states the claim, your $90M seed from Khosla and Radical (August 2026) funds it, and your founders led Nvidia''s 3D and simulation research. One site page and press quotes are your entire public voice, so the first article defines what a simulated world needs to make that learning useful.', '{world-models,linkedin-post,funding-proof}'::text[], '[{"title": "homepage", "publisher": "Veeda AI", "url": "https://veeda.ai/"}, {"title": "Former Nvidia lab leader Sanja Fidler launches Veeda AI", "publisher": "BetaKit", "url": "https://betakit.com/former-nvidia-lab-leader-sanja-fidler-launches-veeda-ai-to-tackle-world-models/"}, {"title": "Sanja Fidler raises over US$90M for Veeda AI", "publisher": "The Logic", "url": "https://thelogic.co/news/exclusive/veeda-ai-sanja-fidler-nvidia/"}]'::jsonb, 0 from companies where slug = 'veeda-4idwaw'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r3-41', 'long_form', 'Trial and Error on Hardware Is Slow and Costly', 'Real robots provide experience nothing else can, and running trial and error on them is slow, expensive and sometimes unsafe. Simulated interaction adds practice only where it transfers, and the test for that is the article.', 'Your site makes the slow-and-costly argument directly and frames simulated reality as infrastructure for all of robotics. The piece that would stand out is the arithmetic on hours of useful experience per dollar, sim versus hardware, with a stated transfer test, and it doubles as a recruiting document.', '{data-economics,long-form,press-proof}'::text[], '[{"title": "homepage", "publisher": "Veeda AI", "url": "https://veeda.ai/"}, {"title": "Ex-Nvidia researchers raise $90M seed for world model startup Veeda", "publisher": "Dealroom", "url": "https://dealroom.co/news/146065-ex-nvidia-researchers-raise-90m-seed-for-world-model-startup-veeda/"}, {"title": "Fidler launches Veeda AI", "publisher": "BetaKit", "url": "https://betakit.com/former-nvidia-lab-leader-sanja-fidler-launches-veeda-ai-to-tackle-world-models/"}]'::jsonb, 1 from companies where slug = 'veeda-4idwaw'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r3-42', 'short_insight', 'Looks Right Versus Responds Right', 'A generated world can look convincing and still teach a robot the wrong lesson. A world model an agent acts inside has to be judged by what happens after the action, and that is harder to evaluate than a frame.', 'Your site specifies multimodal world models for embodied agents to interact with, not video generation. The piece explains how you judge a world by its response to an agent rather than its appearance, naming the evaluation work you are willing to describe.', '{world-model-evaluation,short-insight,founding-thesis}'::text[], '[{"title": "homepage", "publisher": "Veeda AI", "url": "https://veeda.ai/"}, {"title": "Veeda seed coverage", "publisher": "Dealroom", "url": "https://dealroom.co/news/146065-ex-nvidia-researchers-raise-90m-seed-for-world-model-startup-veeda/"}, {"title": "Fidler launches Veeda AI", "publisher": "BetaKit", "url": "https://betakit.com/former-nvidia-lab-leader-sanja-fidler-launches-veeda-ai-to-tackle-world-models/"}]'::jsonb, 2 from companies where slug = 'veeda-4idwaw'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
