-- Import for Virtual Verse Studio (virtualverse-w9eg79). Generated from clients/virtualverse-w9eg79.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('virtualverse-w9eg79', 'Virtual Verse Studio', null, null, 'your NBK Virtugate and museum work, and the questions clients ask before they build in 3D', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'vvs-01', 'short_insight', 'Bank Onboarding in 3D: Measure Retention', 'One 2026 roundup puts VR training use at 22% of large enterprises against 7% of organizations overall. Completion is easy to count, but retention was the actual problem in the brief.', 'Your NBK Virtugate build runs in a browser with a sub-15-second load target, 60 FPS on desktop and 30 to 45 on low-end hardware. Your post says NBK''s retention was weak, but reports no retention results after launch. That is the gap.', '{onboarding,short-insight,browser-3d}'::text[], '[{"title": "NBK Virtugate", "publisher": "Virtual Verse Studio", "url": "https://virtualverse.studio/blogs/inside-nbk-virtugate-unity-webgl-development"}, {"title": "industry statistics report", "publisher": "Treeview", "url": "https://treeview.studio/blog/ar-vr-mr-xr-metaverse-spatial-computing-industry-stats"}]'::jsonb, 0 from companies where slug = 'virtualverse-w9eg79'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'vvs-02', 'short_insight', 'Museum AI Avatars: Design for Disclosure', 'The EU AI Act''s Article 50 has applied since Aug 2, 2026. It requires disclosure when people interact with AI, and notice when emotion recognition or biometric categorisation is used. Real-time visitor tracking in a public gallery needs a disclosure plan before launch.', 'Your blog lists a Meet Eva Here installation that tracked and responded to museum visitors in real time (April 8, 2026). Confirm what it tracked and whether any biometric categorisation was involved before writing.', '{ai-avatars,short-insight,museum-installations}'::text[], '[{"title": "blog index", "publisher": "Virtual Verse Studio", "url": "https://virtualverse.studio/blogs"}, {"title": "Article 50", "publisher": "Morgan Lewis", "url": "https://www.morganlewis.com/blogs/sourcingatmorganlewis/2026/08/eu-ai-acts-transparency-rules-what-went-into-effect-on-2-august"}, {"title": "what applies from Aug 2", "publisher": "Legalithm", "url": "https://www.legalithm.com/en/blog/eu-ai-act-what-applies-2-august-2026"}]'::jsonb, 1 from companies where slug = 'virtualverse-w9eg79'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'vvs-03', 'long_form', 'Meta VR Glasses: Port or Rebuild?', 'Meta announced VR Glasses on Sept 23, 2026 at $1,299 for spring 2027, with the Quest OS and app store. One trade summary says Quest training content should run, but controller-based or peripheral-vision modules may need rework.', 'Your blog already covers Meta Quest onboarding (Immersive Exposure), hazard recognition architecture and Android XR versus Vision Pro versus Quest. A post-Connect port checklist extends that coverage. The summary is a vendor blog, so verify against Meta''s developer documentation.', '{meta-vr-glasses,long-form,porting}'::text[], '[{"title": "Meta VR Glasses", "publisher": "Road to VR", "url": "https://roadtovr.com/meta-vr-glasses-unveiled-price-release-date/"}, {"title": "enterprise training", "publisher": "VR Vision Group", "url": "https://www.vrvisiongroup.com/meta-vr-glasses-enterprise-training/"}, {"title": "blog index", "publisher": "Virtual Verse Studio", "url": "https://virtualverse.studio/blogs"}]'::jsonb, 2 from companies where slug = 'virtualverse-w9eg79'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
