-- Import for VividQ (vividq-uzcfpn). Generated from clients/vividq-uzcfpn.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('vividq-uzcfpn', 'VividQ', 'Darran', 'Darran', 'your holography work with JVCKenwood, iView and Call of Duty, and the questions glasses and car makers ask before they commit to a display', true, to_jsonb('1 long-form article + 1 short insight + 1 LinkedIn post'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r3-25', 'linkedin_post', 'Display Glasses Are 4 Percent of AI Glasses', 'Counterpoint says 96 percent of AI glasses shipped in H1 2026 had no display, while the display segment grows fast from a small base. As displays enter more glasses, the question becomes what changes for the wearer when imagery can sit at different depths.', 'Your position is that per-pixel-depth holography addresses the vergence-accommodation problem that fixed-focus displays carry, and your public proof runs from retina-resolution holograms on a 4K JVCKenwood LCoS (January 2024) to the 2025 Call of Duty holographic display announcement. Your blog has been silent since April 2024, in the year the category took off.', '{computer-generated-holography,linkedin-post,demo-proof}'::text[], '[{"title": "AI Glasses Shipments Surged 263% in H1 2026", "publisher": "Xenospectrum", "url": "https://xenospectrum.com/en/ai-glasses-h1-2026-shipments/"}, {"title": "World''s first retina resolution holograms are here", "publisher": "TNW", "url": "https://thenextweb.com/news/vividq-first-retina-resolution-holograms"}, {"title": "Technology", "publisher": "VividQ", "url": "https://www.vividq.com/technology"}]'::jsonb, 0 from companies where slug = 'vividq-uzcfpn'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r3-26', 'short_insight', 'Meta''s Display Cost Target Versus the Holography Compute Bill', 'Meta has sketched what a mass-market glasses display stack would need to cost, and computed holography is not in most near-term roadmaps. For a glasses maker the open questions are power, compute, image quality and integration cost, in that order.', 'You ran real-time CGH on an Arm Mali mobile GPU in 2020, claim 100 FPS generation today, and hold a patent on a 3D waveguide combiner that removes mechanical IPD adjustment. No public piece from you states what a hologram costs in power per frame, and that number decides the argument.', '{display-cost,short-insight,partner-proof}'::text[], '[{"title": "CES and AR/VR/MR 2026 Quick Takeaways Part 1", "publisher": "KGOnTech", "url": "https://kguttag.com/2026/03/09/ces-ar-vr-mr-2026-quick-takeaways-part-1-android-google-xr-and-meta/"}, {"title": "Arm on mobile holographic display", "publisher": "VividQ", "url": "https://www.vividq.com/news/arm-writes-about-the-magic-and-science-behind-mobile-holographic-display-with-vividq"}, {"title": "Partners", "publisher": "VividQ", "url": "https://www.vividq.com/partners"}]'::jsonb, 1 from companies where slug = 'vividq-uzcfpn'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r3-27', 'long_form', 'Holographic Windshield Film Is Not a Holographic HUD', 'Hyundai Mobis, ZEISS, tesa and Saint-Gobain formed a supply alliance in February 2026 around holographic optical-element windshield film at 10,000-plus nits with a 2029 commercialisation target. That film directs projected light; a computer-generated hologram represents depth.', 'Your CoReality HUD product and your 2021 iView licence for automotive optical modules sit on the other side of that distinction. An automotive buyer needs to know what each approach does, what it needs behind the glass, and what depth the driver actually sees, and VividQ is placed to say it plainly.', '{automotive-hud,long-form,product-proof}'::text[], '[{"title": "Hyundai Mobis Forms Global Alliance for Next-Generation Display Technologies", "publisher": "PR Newswire", "url": "https://www.prnewswire.com/news-releases/hyundai-mobis-forms-global-alliance-for-next-generation-display-technologies-302676003.html"}, {"title": "Products", "publisher": "VividQ", "url": "https://www.vividq.com/products"}, {"title": "VividQ teams up with iView", "publisher": "Cambridge Independent", "url": "https://www.cambridgeindependent.co.uk/business/vividq-teams-up-with-iview-to-bring-holography-to-the-consum-9218172/"}]'::jsonb, 2 from companies where slug = 'vividq-uzcfpn'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
