-- Import for VRAI (vrai-62jbwk). Generated from clients/vrai-62jbwk.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('vrai-62jbwk', 'VRAI', 'Pat', 'Pat', 'your Varjo and Rheinmetall work, and the questions instructors ask before they trust trainee data', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'vrai-01', 'long_form', 'What a 1:12 Instructor Ratio Must Show', 'Varjo and VRAI jointly reported on April 14, 2026 that first joint deployments moved the instructor-to-trainee ratio from approximately 1:3 to 1:12 without added instructor workload. This is joint company reporting, with no named deployment, sample, period or workload measure.', 'Your April 15, 2026 post names Rheinmetall and the Irish Defence Forces as customers in the first joint deployments but does not tie the ratio to either. It has not been independently validated. No article on your site explains how an instructor assessment dataset must be built before a staffing ratio claim holds.', '{training-metrics,long-form,company-reported}'::text[], '[{"title": "Varjo and VRAI announce strategic partnership", "publisher": "Varjo", "url": "https://www.varjo.com/news/varjo-and-vrai-announce-strategic-partnership-to-bring-data-driven-insights-to-military-training"}, {"title": "VRAI and Varjo announce strategic partnership", "publisher": "VRAI", "url": "https://www.vraisimulation.com/post/vrai-and-varjo-announce-strategic-partnership-to-bring-data-driven-insights-to-military-training"}]'::jsonb, 0 from companies where slug = 'vrai-62jbwk'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'vrai-02', 'short_insight', 'What Eye Tracking Measures in a Trainee', 'VRAI''s About page describes a 2018 UN Mine Action Service project in Somalia whose after action review used gaze data to tell users how many IEDs they identified and how many they missed. Eye tracking and heart rate variability supply signals to an instructor, and the article explains what each can support and where each stops.', 'Your December 3, 2024 cognitive load post combines eye tracking and heart rate variability in a near real-time instructor dashboard, shown at I/ITSEC on a VBS4 driving simulator, with no numbers. Neither signal alone shows a trainee''s cognitive load or readiness. No article on your site explains what near real-time means for that dashboard or what validation sits behind it.', '{biometric-sensing,short-insight,company-reported}'::text[], '[{"title": "About", "publisher": "VRAI", "url": "https://www.vraisimulation.com/about"}]'::jsonb, 1 from companies where slug = 'vrai-62jbwk'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'vrai-03', 'short_insight', 'A Signed Partnership Is Not Qualified Training', 'VRAI and Rheinmetall announced a strategic partnership on December 3, 2025 at I/ITSEC, with an initial XR driving simulator for armor crews and possible expansion, per the release as our researcher read it. The post does not call it a contract and reports no delivery.', 'Your post is an announcement without delivery dates. Its silence on delivery does not show that nothing was delivered. No article on your site explains what separates a partnership from a trainer a defense customer accepts into service.', '{defense-procurement,short-insight,announcement}'::text[], '[{"title": "Home", "publisher": "VRAI", "url": "https://www.vraisimulation.com"}]'::jsonb, 2 from companies where slug = 'vrai-62jbwk'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
