-- Import for VR Vision Group (vrvision-5lrb85). Generated from clients/vrvision-5lrb85.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('vrvision-5lrb85', 'VR Vision Group', 'Roni', 'Roni', 'your Avangrid, Toronto Hydro and wind turbine work, and the questions utilities ask before they trust VR competency', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'vrv-01', 'long_form', 'What Competency Means in Utility VR Training', 'VR Vision reports that Avangrid maintenance technicians reached competency 65% faster than with traditional training, with hundreds of Quest headsets, from 2019 to 2024. The case study states no baseline, sample or measurer. The 24 states describe Avangrid''s operating footprint, not an evaluation across them.', 'Your Avangrid case study was published October 3, 2023 and updated September 28, 2026, and it is vendor-reported. No article on your site explains how competency was defined, who assessed it and what the comparison group did.', '{competency-metrics,long-form,company-reported}'::text[], '[{"title": "Avangrid case study", "publisher": "VR Vision Group", "url": "https://www.vrvisiongroup.com/case-study/avangrid/"}, {"title": "Ultimate guide to VR training", "publisher": "VR Vision Group", "url": "https://www.vrvisiongroup.com/ultimate-guide-vr-training/"}]'::jsonb, 0 from companies where slug = 'vrvision-5lrb85'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'vrv-02', 'short_insight', 'SCADA Fault Codes Drive Wind Turbine Scenarios', 'VR Vision''s June 27, 2025 wind turbine post describes six modules built with Avangrid on real SCADA scenarios. It names fault codes such as 5212, a thermal relay failure, and walks the trainee through schematics, hot-cold-hot voltage testing, lockout tagout and contactor replacement with HMI verification. The post cites 49.9% projected wind technician job growth from 2024 to 2034 from BLS, a figure we could verify only second hand.', 'Your post is by Roni Cerga and mentions real-time performance tracking in Vision Portal. It does not explain how scenarios are authored or how a trainee''s response is scored. No article on your site explains how the team chooses which fault-code decisions to rehearse and how it scores the response.', '{scenario-design,short-insight,company-reported}'::text[], '[{"title": "VR training for wind turbine technicians, June 27, 2025", "publisher": "VR Vision Group", "url": "https://www.vrvisiongroup.com/vr-training-wind-turbine-technicians/"}, {"title": "Avangrid case study", "publisher": "VR Vision Group", "url": "https://www.vrvisiongroup.com/case-study/avangrid/"}]'::jsonb, 1 from companies where slug = 'vrvision-5lrb85'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'vrv-03', 'short_insight', 'Simulating Switchgear Hazards You Cannot Rehearse', 'VR Vision''s Toronto Hydro case study describes digital twins of switchgear and underground vaults, multiplayer fuse replacement and isolate-and-ground procedures on SF6 switchgear, with guided and real-time evaluation modes on 40 headsets. The case study reports a vendor-reported 30% reduction in technician time-to-train, with no baseline.', 'Your February 18, 2026 data center post gives a different Toronto Hydro result, 2,000+ technicians and a 30% error reduction within 90 days. That is a different outcome and denominator, so the article uses one metric and names it. No article on your site explains how the evaluation mode scores an isolate-and-ground step.', '{hazard-simulation,short-insight,company-reported}'::text[], '[{"title": "Toronto Hydro case study", "publisher": "VR Vision Group", "url": "https://www.vrvisiongroup.com/case-study/toronto-hydro/"}, {"title": "Hydro One case study", "publisher": "VR Vision Group", "url": "https://www.vrvisiongroup.com/case-study/hydro-one/"}, {"title": "Ultimate guide to VR training", "publisher": "VR Vision Group", "url": "https://www.vrvisiongroup.com/ultimate-guide-vr-training/"}]'::jsonb, 2 from companies where slug = 'vrvision-5lrb85'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
