-- Import for Vsim (vsim-93oi1y). Generated from clients/vsim-93oi1y.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('vsim-93oi1y', 'Vsim', 'Michelle', 'Michelle', 'your founders'' simulation work and the questions robotics teams ask before they trust a faster simulator', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-19', 'short_insight', 'Why Simulation Speed Matters on the Robot Itself', 'Nvidia''s Newton 1.0 (March 2026) sells thousands of parallel environments on datacenter GPUs. Running a simulator on the hardware a robot carries is a different engineering problem, and the two are complements, not rivals.', 'The BBC''s September 2026 feature reports your simulator running on compute carried by Freddo, with Storey describing it looking about a second ahead across 20,000 combinations, his description rather than a published benchmark. What has to fit the onboard budget and what still belongs in large-scale training is the article.', '{on-robot-simulation,short-insight,press-proof}'::text[], '[{"title": "Robotics: Firms race to improve robot training systems", "publisher": "BBC", "url": "https://www.bbc.co.uk/news/articles/c79g0j3d4q9o"}, {"title": "Newton adds contact-rich manipulation and locomotion capabilities", "publisher": "NVIDIA Developer Blog", "url": "https://developer.nvidia.com/blog/newton-adds-contact-rich-manipulation-and-locomotion-capabilities-for-industrial-robotics"}, {"title": "Isaac Sim 6.0 Early Developer Release", "publisher": "NVIDIA Forums", "url": "https://forums.developer.nvidia.com/t/announcement-isaac-sim-6-0-early-developer-release-for-gtc26/363709"}]'::jsonb, 0 from companies where slug = 'vsim-93oi1y'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-20', 'linkedin_post', 'What Legacy Contact Solvers Cost on GPUs', 'Isaac Sim 6.0 now ships two physics backends, which makes solver architecture a live question in the field. Storey''s public position is that many familiar physics algorithms were built before GPUs became central to robot learning.', 'Your founders spent a decade each on PhysX and Isaac Sim at Nvidia, and your 2024 round cited an up-to-100x RL training speedup that has no public baseline. A piece showing one contact-heavy task, where the mismatch costs time and what you do differently, would be your first published content and would make the 100x claim checkable.', '{physics-simulation,linkedin-post,founder-credibility}'::text[], '[{"title": "Robotics: Firms race to improve robot training systems", "publisher": "BBC", "url": "https://www.bbc.co.uk/news/articles/c79g0j3d4q9o"}, {"title": "Isaac Sim 6.0 Early Developer Release", "publisher": "NVIDIA Forums", "url": "https://forums.developer.nvidia.com/t/announcement-isaac-sim-6-0-early-developer-release-for-gtc26/363709"}, {"title": "Vsim, founded by Nvidia alums, raises $21.5M", "publisher": "TechCrunch", "url": "https://techcrunch.com/2024/09/25/vsim-founded-by-nvidia-alums-raises-21-5m-for-robotics-simulation-tech/"}]'::jsonb, 1 from companies where slug = 'vsim-93oi1y'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'r2-21', 'short_insight', 'Speed Versus Realism in Sim-to-Real', 'NEURA partnered with Dassault in April 2026 specifically on the sim-to-real gap, and a faster simulator only helps when the behaviour it teaches survives contact with the real world. Where a simulator accepts approximation is a design decision, not a detail.', 'Lu describes Vsim''s approach as reduced approximation, and the BBC piece quotes Cambridge''s Rika Antonova on the limits of simulated worlds. Freddo''s bottle grasp is a demonstration, not proof of transfer across robots; the article is where you accept approximation, where you refuse it, and how you test the difference on hardware.', '{sim-to-real,short-insight,press-proof}'::text[], '[{"title": "Robotics: Firms race to improve robot training systems", "publisher": "BBC", "url": "https://www.bbc.co.uk/news/articles/c79g0j3d4q9o"}, {"title": "NEURA Robotics to raise up to $1.4B in Series C", "publisher": "The Robot Report", "url": "https://www.therobotreport.com/neura-robotics-raise-up-1-4b-in-series-c-funding-physical-ai/"}, {"title": "Newton and Isaac Sim", "publisher": "NVIDIA Perspectives", "url": "https://perspectives.nvidia.com/isaac-sim/newtons-integration-isaac-sim-and-isaac-lab/"}]'::jsonb, 2 from companies where slug = 'vsim-93oi1y'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
