-- Import for XYZ Reality (xyzreality-vtfkwj). Generated from clients/xyzreality-vtfkwj.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('xyzreality-vtfkwj', 'XYZ Reality', 'David', 'David', 'your hyperscale and retrofit projects, and the questions delivery teams ask before they trust as-built data', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'xyz-01', 'short_insight', 'Verified-Built Evidence for Grid Allocation', 'New York''s governor announced on July 14, 2026 a pause of up to one year on discretionary state environmental permits for new hyperscale data centers not already deemed complete, while a generic environmental impact statement is developed. On June 3, 2026 an XYZ Reality VP argued in Data Centre Review that grid queues should weigh delivery signals such as engineering validation.', 'Your Applied Digital announcement reports 450 MW of planned critical IT load across three hyperscale buildings and 600 MW of total capacity supported. That is project capacity, not power delivered, and not a New York project. The page carries a January 12 byline and a January 13 announcement date. No article on your site explains which as-built milestones a regulator could check.', '{data-center-permitting,short-insight,company-reported}'::text[], '[{"title": "600MW and growing", "publisher": "XYZ Reality", "url": "https://www.xyzreality.com/resources/600mw-and-growing-xyz-reality-expands-partnership-with-applied-digital-to-accelerate-ai-factory-delivery"}, {"title": "first statewide moratorium on new hyperscale data centers", "publisher": "Governor of New York", "url": "https://www.governor.ny.gov/news/first-statewide-moratorium-new-hyperscale-data-centers-launched-governor-kathy-hochul"}]'::jsonb, 0 from companies where slug = 'xyzreality-vtfkwj'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'xyz-02', 'short_insight', 'How Portfolio Schedules Become Comparable', 'XYZ Reality''s portfolio case study reports 408 days saved across seven hyperscale projects in six countries, using Schedule Performance Index tracking, cross-project benchmarking and client-provided financial inputs. The figure is a company-modeled estimate and not an independent audit. The case study covers the project controls product, not AR.', 'Your page reports $135M total impact and 10x ROI after service fees for a confidential operator, labeled client-validated. The case already describes cross-project benchmarking. No article on your site explains how schedules from different contractors and countries were normalized before they were compared.', '{project-controls,short-insight,company-estimate}'::text[], '[{"title": "Redefining data center portfolio delivery", "publisher": "XYZ Reality", "url": "https://www.xyzreality.com/resources/redefining-data-center-portfolio-delivery"}, {"title": "From damage control to delivery, $5.5M saved", "publisher": "XYZ Reality", "url": "https://www.xyzreality.com/resources/from-damage-control-to-delivery-north-star-one-developers-journey-to-5.5m-saved"}]'::jsonb, 1 from companies where slug = 'xyzreality-vtfkwj'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'xyz-03', 'long_form', 'Which Reference Wins When Drawings Are Wrong', 'XYZ Reality''s pharma retrofit page reports discrepancies up to 750 mm between design positions and exposed structure, found during inspections in demolition with Atom and Engineering Grade AR. That figure is the size of a discovered error on one anonymous Irish project, not an accuracy specification.', 'Millimetre accuracy appears only as a marketing claim in a November 2021 Atom launch article, and no tolerance figure appears on the pages we opened. No article on your site explains the reference datum, the survey control, the registration checks and the tolerance stack.', '{as-built-verification,long-form,published-result}'::text[], '[{"title": "Prevent structural rework in demolition", "publisher": "XYZ Reality", "url": "https://www.xyzreality.com/resources/prevent-structural-rework-demolition"}, {"title": "Our journey", "publisher": "XYZ Reality", "url": "https://www.xyzreality.com/resources/xyz-reality-journey"}]'::jsonb, 2 from companies where slug = 'xyzreality-vtfkwj'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
