-- Import for YORD (yord-y6ea9x). Generated from clients/yord-y6ea9x.json; safe to re-run.
insert into companies (slug, name, contact_first_name, greeting_name, intro_basis, email_known, direction_shape, offer_text, unlock_mode, show_scarcity, is_internal)
values ('yord-y6ea9x', 'YORD', null, null, 'your Škoda, Bentley and Sparta work, and the questions brands ask before they commission an experience', true, to_jsonb('1 long-form article + 2 short insights'::text), null, 'call', false, false)
on conflict (slug) do update set name = excluded.name, contact_first_name = excluded.contact_first_name, greeting_name = excluded.greeting_name, intro_basis = excluded.intro_basis, email_known = excluded.email_known, direction_shape = excluded.direction_shape, unlock_mode = excluded.unlock_mode, show_scarcity = excluded.show_scarcity, is_internal = excluded.is_internal;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'yord-01', 'short_insight', 'Vision Pro Showrooms: What Škoda Teaches', 'Vision Pro has reportedly sold about 600,000 units in total, and a lighter successor is not expected before late 2028. A premium brand can still justify it when the headset serves a small, high-intent audience.', 'Your Škoda Elroq and Epiq experience offers VR exploration or life-size mixed reality placement. Your Bentley app adds a haptic panel with real material samples and 3600 x 3200 per eye video. No audience numbers are published. Your Sept 4, 2026 configurator cost guide exists, so keep this on Vision Pro, not web configurators.', '{vision-pro,short-insight,mixed-reality}'::text[], '[{"title": "Škoda Vision Pro", "publisher": "YORD", "url": "https://yordstudio.com/project/apple-vision-pro-skoda/"}, {"title": "Bentley", "publisher": "YORD", "url": "https://yordstudio.com/project/vr-xr-experience-bentley/"}, {"title": "Vision Pro sales", "publisher": "MacRumors", "url": "https://www.macrumors.com/2026/04/29/apple-vision-pro-m5-flop/"}, {"title": "successor report", "publisher": "The Apple Post", "url": "https://www.theapplepost.com/2026/09/27/72741/work-continues-on-lighter-apple-vision-pro-successor-report-says/"}]'::jsonb, 0 from companies where slug = 'yord-y6ea9x'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'yord-02', 'short_insight', 'AI Try-On Mirrors: Disclose the AI', 'The EU AI Act''s Article 50 has applied since Aug 2, 2026, requiring disclosure when people interact with AI, with fines up to €15 million or 3% of turnover. AI-generated try-on images also need marking, with a Dec 2, 2026 grace period for systems already live.', 'Your Sparta AI Mirror with Footballmania, ČSOB and Mastercard lets account holders try on merchandise through AI-generated images. It has an interactive quiz and QR sharing. No sales lift is published, and you are Prague-based, so EU rules apply directly.', '{ai-try-on,short-insight,retail-experience}'::text[], '[{"title": "Sparta AI Mirror", "publisher": "YORD", "url": "https://yordstudio.com/project/ai-try-on-booth-sparta/"}, {"title": "Article 50", "publisher": "Morgan Lewis", "url": "https://www.morganlewis.com/blogs/sourcingatmorganlewis/2026/08/eu-ai-acts-transparency-rules-what-went-into-effect-on-2-august"}, {"title": "what applies from Aug 2", "publisher": "Legalithm", "url": "https://www.legalithm.com/en/blog/eu-ai-act-what-applies-2-august-2026"}]'::jsonb, 1 from companies where slug = 'yord-y6ea9x'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
insert into cards (company_id, card_key, format, title, angle, evidence, tags, sources, sort_order)
select id, 'yord-03', 'long_form', 'Luxury XR After Vision Pro: Design to Port', 'Meta announced VR Glasses on Sept 23, 2026 at $1,300 for spring 2027, while Apple''s lighter successor is not expected before late 2028. Luxury brands should build experience logic that moves across headsets.', 'Your Škoda, Bentley and ASAHI projects are all Vision Pro builds, and Bentley blends image target recognition with life-size configuration. The article asks which pieces are device-specific and which would port.', '{luxury-xr,long-form,portability}'::text[], '[{"title": "Meta VR Glasses", "publisher": "Road to VR", "url": "https://roadtovr.com/meta-vr-glasses-unveiled-price-release-date/"}, {"title": "successor report", "publisher": "The Apple Post", "url": "https://www.theapplepost.com/2026/09/27/72741/work-continues-on-lighter-apple-vision-pro-successor-report-says/"}, {"title": "Bentley", "publisher": "YORD", "url": "https://yordstudio.com/project/vr-xr-experience-bentley/"}, {"title": "Škoda Vision Pro", "publisher": "YORD", "url": "https://yordstudio.com/project/apple-vision-pro-skoda/"}]'::jsonb, 2 from companies where slug = 'yord-y6ea9x'
on conflict (company_id, card_key) do update set format = excluded.format, title = excluded.title, angle = excluded.angle, evidence = excluded.evidence, tags = excluded.tags, sources = excluded.sources, sort_order = excluded.sort_order;
